import type { CommandHandler } from './commandTypes';

// cmd modülleri
import {
  cmdInterface,
  cmdShutdown,
  cmdNoShutdown,
  cmdSpeed,
  cmdDuplex,
  cmdDescription,
  cmdNoDescription,
} from './interface/cmd.interface';

import {
  cmdNoSwitchport,
  cmdSwitchportMode,
  cmdSwitchportAccessVlan,
  cmdSwitchportTrunkNativeVlan,
  cmdSwitchportTrunkAllowedVlan,
  cmdSwitchportPortSecurity,
  cmdSwitchportPortSecurityMaximum,
  cmdSwitchportPortSecurityViolation,
  cmdSwitchportPortSecuritySticky,
  cmdNoSwitchportMode,
  cmdNoSwitchportAccessVlan,
  cmdNoSwitchportPortSecurity,
  cmdSwitchportNonegotiate,
  cmdSwitchportVoiceVlan,
  cmdSwitchportProtected,
  cmdSwitchportBlock,
  cmdSwitchportPortSecurityMacAddress,
  cmdSwitchportTrunkEncapsulation,
  cmdSwitchportPortSecurityAgingTime,
  cmdSwitchportPortSecurityAgingType,
} from './interface/cmd.switchport';

import {
  cmdIpAddress,
  cmdNoIpAddress,
  cmdIpDefaultGateway,
  cmdNoIpDefaultGateway,
  cmdIpv6Address,
  cmdIpv6TrafficFilter,
  cmdIpv6Rip,
  cmdIpv6Ospf,
  cmdIpOspfArea,
  cmdNoIpOspfArea,
  cmdNoIpv6Rip,
  cmdIpv6DhcpServer,
  cmdNoIpv6Ospf,
  cmdIpHelperAddress,
  cmdNoIpHelperAddress,
  cmdIpNatInside,
  cmdIpNatOutside,
  cmdNoIpNatInside,
  cmdNoIpNatOutside,
  cmdIpAccessGroup,
  cmdNoIpAccessGroup,
  cmdIpProxyArp,
  cmdNoIpProxyArp,
  cmdIpVerifySource,
  cmdIpDhcpSnoopingTrust,
  cmdNoIpDhcpSnoopingTrust,
  cmdIpArpInspectionTrust,
  cmdNoIpArpInspectionTrust,
  cmdIpv6NdSuppressRa,
  cmdNoIpv6NdSuppressRa,
} from './interface/cmd.ipAddress';

import {
  cmdSpanningTreePortfast,
  cmdSpanningTreeBpduguard,
  cmdSpanningTreeBpduguardDisable,
  cmdSpanningTreeCost,
  cmdNoSpanningTreeCost,
  cmdSpanningTreePriority,
  cmdNoSpanningTree,
  cmdChannelGroup,
  cmdNoChannelGroup,
} from './interface/cmd.spanningTree';

import {
  cmdStandbyIp,
  cmdStandbyPriority,
  cmdStandbyIpv6,
  cmdStandbyPreempt,
  cmdSsid,
  cmdEncryption,
  cmdWlan,
  cmdNoWlan,
  cmdSecurityWpaPsk,
  cmdSecurityWepKey,
  cmdChannel,
  cmdStationRole,
  cmdNoCdpEnable,
  cmdNoUdld,
  cmdNoKeepalive,
  cmdDebug,
  cmdNoDebug,
  cmdMonitorSession,
  cmdNoMonitorSession,
  cmdAccessList,
  cmdNoAccessList,
  cmdCdpEnable,
  cmdEncapsulationDot1q,
  cmdEncapsulationHdlc,
  cmdEncapsulationPpp,
  cmdNoEncapsulation,
  cmdClockRate,
  cmdNoClockRate,
  cmdPppAuthPap,
  cmdPppAuthChap,
  cmdNoPppAuth,
  cmdPppPapSentUsername,
  cmdStormControl,
  cmdStormControlAction,
  cmdMlsQosTrust,
  cmdMlsQosCos,
  cmdBandwidth,
  cmdDelay,
  cmdMtu,
  cmdKeepalive,
  cmdUdldEnable,
  cmdChannelProtocol,
  cmdDirectedBroadcast,
  cmdCarrierDelay,
  cmdLoadInterval,
  cmdPowerInline,
  cmdPowerInlineConsumption,
  cmdArpInspectionLimit,
  cmdPriorityQueueOut,
  cmdQueueSet,
  cmdTxQueue,
  cmdVrrpIp,
  cmdVrrpPriority,
  cmdVrrpPreempt,
} from './interface/cmd.misc';

// Interface-level komutlar (interface, shutdown, speed, duplex, switchport, ip address, vs.)

export const interfaceHandlers: Record<string, CommandHandler> = {
  'interface': cmdInterface,
  'interface range': cmdInterface,
  'shutdown': cmdShutdown,
  'no shutdown': cmdNoShutdown,
  'speed': cmdSpeed,
  'duplex': cmdDuplex,
  'description': cmdDescription,
  'switchport mode': cmdSwitchportMode,
  'switchport access vlan': cmdSwitchportAccessVlan,
  'switchport trunk native vlan': cmdSwitchportTrunkNativeVlan,
  'switchport trunk allowed vlan': cmdSwitchportTrunkAllowedVlan,
  'switchport port-security': cmdSwitchportPortSecurity,
  'switchport port-security maximum': cmdSwitchportPortSecurityMaximum,
  'switchport port-security violation': cmdSwitchportPortSecurityViolation,
  'switchport port-security mac-address sticky': cmdSwitchportPortSecuritySticky,
  'no switchport': cmdNoSwitchport,
  'spanning-tree portfast': cmdSpanningTreePortfast,
  'spanning-tree bpduguard': cmdSpanningTreeBpduguard,
  'ip address': cmdIpAddress,
  'no ip address': cmdNoIpAddress,
  'ip default-gateway': cmdIpDefaultGateway,
  'no ip default-gateway': cmdNoIpDefaultGateway,
  'wlan': cmdWlan,
  'no wlan': cmdNoWlan,
  'security wpa psk set-key': cmdSecurityWpaPsk,
  'security wep key set-key': cmdSecurityWepKey,
  'channel': cmdChannel,
  'station-role': cmdStationRole,
  'ssid': cmdSsid,
  'encryption': cmdEncryption,
  // No commands for interface
  'no description': cmdNoDescription,
  'no switchport mode': cmdNoSwitchportMode,
  'no switchport access vlan': cmdNoSwitchportAccessVlan,
  'no switchport port-security': cmdNoSwitchportPortSecurity,
  'no cdp enable': cmdNoCdpEnable,
  'no udld': cmdNoUdld,
  'no ip proxy-arp': cmdNoIpProxyArp,
  'no keepalive': cmdNoKeepalive,
  'no spanning-tree': cmdNoSpanningTree,
  // Debug and monitor
  'debug': cmdDebug,
  'no debug': cmdNoDebug,
  'undebug all': cmdNoDebug,
  'undebug': cmdNoDebug,
  'monitor session': cmdMonitorSession,
  'no monitor session': cmdNoMonitorSession,
  // Access-list
  'access-list': cmdAccessList,
  'no access-list': cmdNoAccessList,
  'ip access-group': cmdIpAccessGroup,
  'no ip access-group': cmdNoIpAccessGroup,
  // EtherChannel
  'channel-group': cmdChannelGroup,
  'no channel-group': cmdNoChannelGroup,
  // DHCP relay
  'ip helper-address': cmdIpHelperAddress,
  'no ip helper-address': cmdNoIpHelperAddress,
  // Switchport extras
  'switchport nonegotiate': cmdSwitchportNonegotiate,
  'switchport voice vlan': cmdSwitchportVoiceVlan,
  // CDP
  'cdp enable': cmdCdpEnable,
  // Spanning-tree extras
  'spanning-tree bpduguard enable': cmdSpanningTreeBpduguard,
  'spanning-tree bpduguard disable': cmdSpanningTreeBpduguardDisable,
  'no spanning-tree bpduguard': cmdSpanningTreeBpduguardDisable,
  'no spanning-tree bpduguard enable': cmdSpanningTreeBpduguardDisable,
  'spanning-tree cost': cmdSpanningTreeCost,
  'no spanning-tree cost': cmdNoSpanningTreeCost,
  'spanning-tree priority': cmdSpanningTreePriority,
  'ipv6 address': cmdIpv6Address,
  'ipv6 nd suppress-ra': cmdIpv6NdSuppressRa,
  'no ipv6 nd suppress-ra': cmdNoIpv6NdSuppressRa,
  'ipv6 rip enable': cmdIpv6Rip,
  'ipv6 ospf area': cmdIpv6Ospf,
  'ip ospf area': cmdIpOspfArea,
  'no ip ospf area': cmdNoIpOspfArea,
  'ipv6 dhcp server': cmdIpv6DhcpServer,
  'no ipv6 rip enable': cmdNoIpv6Rip,
  'no ipv6 ospf area': cmdNoIpv6Ospf,
  'switchport voice': cmdSwitchportVoiceVlan,
  'channel-protocol': cmdChannelProtocol,
  'priority-queue out': cmdPriorityQueueOut,
  'queue-set': cmdQueueSet,
  'tx-queue': cmdTxQueue,
  'power inline': cmdPowerInline,
  'power inline consumption': cmdPowerInlineConsumption,
  'ip directed-broadcast': (state, input, _ctx) => cmdDirectedBroadcast(state, input, true),
  'no ip directed-broadcast': (state, input, _ctx) => cmdDirectedBroadcast(state, input, false),
  'ip arp inspection limit': cmdArpInspectionLimit,
  'carrier-delay': cmdCarrierDelay,
  'delay': cmdDelay,
  'load-interval': cmdLoadInterval,
  'mtu': cmdMtu,
  'switchport trunk encapsulation': cmdSwitchportTrunkEncapsulation,
  'encapsulation dot1q': cmdEncapsulationDot1q,
  'encapsulation hdlc': cmdEncapsulationHdlc,
  'encapsulation ppp': cmdEncapsulationPpp,
  'no encapsulation': cmdNoEncapsulation,
  'clock rate': cmdClockRate,
  'no clock rate': cmdNoClockRate,
  'ppp authentication pap': cmdPppAuthPap,
  'ppp authentication chap': cmdPppAuthChap,
  'no ppp authentication': cmdNoPppAuth,
  'ppp pap sent-username': cmdPppPapSentUsername,
  'switchport protected': cmdSwitchportProtected,
  'switchport block': cmdSwitchportBlock,
  'switchport port-security mac-address': cmdSwitchportPortSecurityMacAddress,
  'switchport port-security aging time': cmdSwitchportPortSecurityAgingTime,
  'switchport port-security aging type': cmdSwitchportPortSecurityAgingType,
  'storm-control': cmdStormControl,
  'storm-control action': cmdStormControlAction,
  'mls qos trust': cmdMlsQosTrust,
  'mls qos cos': cmdMlsQosCos,
  'ip dhcp snooping trust': cmdIpDhcpSnoopingTrust,
  'no ip dhcp snooping trust': cmdNoIpDhcpSnoopingTrust,
  'ip arp inspection trust': cmdIpArpInspectionTrust,
  'no ip arp inspection trust': cmdNoIpArpInspectionTrust,
  'bandwidth': cmdBandwidth,
  'keepalive': cmdKeepalive,
  'ip proxy-arp': cmdIpProxyArp,
  'ip verify source': cmdIpVerifySource,
  'udld enable': cmdUdldEnable,
  'udld port': cmdUdldEnable,
  'standby ip': cmdStandbyIp,
  'standby priority': cmdStandbyPriority,
  'standby ipv6': cmdStandbyIpv6,
  'standby preempt': cmdStandbyPreempt,
  'vrrp ip': cmdVrrpIp,
  'vrrp priority': cmdVrrpPriority,
  'vrrp preempt': cmdVrrpPreempt,
  'vrrp': cmdVrrpIp,
  'ipv6 traffic-filter': cmdIpv6TrafficFilter,
  'no ipv6 traffic-filter': cmdIpv6TrafficFilter,
  'ip nat inside': cmdIpNatInside,
  'no ip nat inside': cmdNoIpNatInside,
  'ip nat outside': cmdIpNatOutside,
  'no ip nat outside': cmdNoIpNatOutside,
};
