import type { GuidedStep } from '../guidedMode.types';

export const cliLessonsSwitch: GuidedStep[] = [
  // ===== TÜM SWITCH İŞLEMLERİ (1-52) =====
  // Bölüm 1: Temel Mod Komutları (Switch)
  {
    id: 'cli-lesson-1-1a',
    order: 1,
    sectionTitle: { tr: 'Bölüm 1: Temel Mod Komutları (Switch)', en: 'Section 1: Basic Mode Commands (Switch)' },
    title: { tr: 'Enable Komutu', en: 'Enable Command' },
    description: { tr: 'Ayrıcalıklı moda geçmek için enable komutunu kullanın', en: 'Use enable command to enter privileged mode' },
    hint: { tr: 'enable', en: 'enable' },
    checkType: 'command',
    checkParams: { commandPattern: 'enable' },
    completed: false,
    points: 5
  },
  {
    id: 'cli-lesson-1-1b',
    order: 2,
    title: { tr: 'Disable Komutu', en: 'Disable Command' },
    description: { tr: 'Kullanıcı moduna dönmek için disable komutunu kullanın', en: 'Use disable command to return to user mode' },
    hint: { tr: 'SW-Lab: disable yazın', en: 'SW-Lab: Type disable' },
    checkType: 'command',
    checkParams: { commandPattern: 'disable' },
    completed: false,
    points: 5
  },
  {
    id: 'cli-lesson-1-1c',
    order: 3,
    title: { tr: 'Help Komutu', en: 'Help Command' },
    description: { tr: 'Yardım sistemini kullanın', en: 'Use the help system' },
    hint: { tr: 'SW-Lab: help yazın', en: 'SW-Lab: Type help' },
    checkType: 'command',
    checkParams: { commandPattern: 'help' },
    completed: false,
    points: 5
  },
  {
    id: 'cli-lesson-1-3a',
    order: 4,
    title: { tr: 'Konfigürasyonu Görüntüle', en: 'View Configuration' },
    description: { tr: 'show running-config komutunu kullanın', en: 'Use show running-config command' },
    hint: { tr: 'SW-Lab: show running-config yazın', en: 'SW-Lab: Type show running-config' },
    checkType: 'command',
    checkParams: { commandPattern: 'show running-config' },
    completed: false,
    points: 10
  },
  {
    id: 'cli-lesson-1-3b',
    order: 5,
    title: { tr: 'Konfigürasyonu Kaydet', en: 'Save Configuration' },
    description: { tr: 'write memory komutunu kullanın', en: 'Use write memory command' },
    hint: { tr: 'SW-Lab: write memory yazın', en: 'SW-Lab: Type write memory' },
    checkType: 'command',
    checkParams: { commandPattern: 'write memory' },
    completed: false,
    points: 10
  },
  // Bölüm 2: Global Konfigürasyon (Switch)
  {
    id: 'cli-lesson-2-1a',
    order: 6,
    sectionTitle: { tr: 'Bölüm 2: Global Konfigürasyon (Switch)', en: 'Section 2: Global Configuration (Switch)' },
    title: { tr: 'Hostname Ayarla', en: 'Set Hostname' },
    description: { tr: 'Switch\'e SW-Lab ismini verin', en: 'Give the switch the name SW-Lab' },
    hint: { tr: 'SW-Lab: hostname SW-Lab yazın', en: 'SW-Lab: Type hostname SW-Lab' },
    checkType: 'command',
    checkParams: { commandPattern: 'hostname SW-Lab' },
    completed: false,
    points: 10
  },
  {
    id: 'cli-lesson-2-1b',
    order: 7,
    title: { tr: 'Banner Ayarla', en: 'Set Banner' },
    description: { tr: 'Giriş karşılama mesajı (MOTD) tanımlayın', en: 'Set a message of the day (MOTD) banner' },
    hint: { tr: 'SW-Lab: banner motd #Welcome# yazın', en: 'SW-Lab: Type banner motd #Welcome#' },
    checkType: 'command',
    checkParams: { commandPattern: 'banner motd' },
    completed: false,
    points: 10
  },
  {
    id: 'cli-lesson-2-1c',
    order: 8,
    title: { tr: 'Enable Secret Ayarla', en: 'Set Enable Secret' },
    description: { tr: 'Enable secret komutunu kullanın', en: 'Learn enable secret command' },
    hint: { tr: 'enable secret password', en: 'enable secret password' },
    checkType: 'command',
    checkParams: { commandPattern: 'enable secret' },
    completed: false,
    points: 10
  },
  {
    id: 'cli-lesson-2-2a',
    order: 9,
    title: { tr: 'DNS Sunucusu Ayarla', en: 'Set DNS Server' },
    description: { tr: 'DNS sunucusu komutunu kullanın', en: 'Learn DNS server command' },
    hint: { tr: 'SW-Lab: ip name-server 8.8.8.8 yazın', en: 'SW-Lab: Type ip name-server 8.8.8.8' },
    checkType: 'command',
    checkParams: { commandPattern: 'ip name-server' },
    completed: false,
    points: 10
  },
  {
    id: 'cli-lesson-2-2b',
    order: 10,
    title: { tr: 'Saat Dilimi Ayarla', en: 'Set Timezone' },
    description: { tr: 'Saat dilimi komutunu kullanın', en: 'Learn timezone command' },
    hint: { tr: 'SW-Lab: clock timezone UTC 0 yazın', en: 'SW-Lab: Type clock timezone UTC 0' },
    checkType: 'command',
    checkParams: { commandPattern: 'clock timezone' },
    completed: false,
    points: 10
  },
  {
    id: 'cli-lesson-2-2c',
    order: 11,
    title: { tr: 'NTP Sunucusu Ayarla', en: 'Set NTP Server' },
    description: { tr: 'NTP sunucusu komutunu kullanın', en: 'Learn NTP server command' },
    hint: { tr: 'SW-Lab: ntp server 192.168.1.1 yazın', en: 'SW-Lab: Type ntp server 192.168.1.1' },
    checkType: 'command',
    checkParams: { commandPattern: 'ntp server' },
    completed: false,
    points: 10
  },
  // Bölüm 3: Arayüz Konfigürasyonu (Switch)
  {
    id: 'cli-lesson-3-1a',
    order: 12,
    sectionTitle: { tr: 'Bölüm 3: Arayüz Konfigürasyonu (Switch)', en: 'Section 3: Interface Configuration (Switch)' },
    title: { tr: 'Arayüz Seçimi', en: 'Interface Selection' },
    description: { tr: 'GigabitEthernet 1/0/1 arayüzüne girin', en: 'Enter GigabitEthernet 1/0/1 interface' },
    hint: { tr: 'SW-Lab: interface gi1/0/1 yazın', en: 'SW-Lab: Type interface gi1/0/1' },
    checkType: 'command',
    checkParams: { commandPattern: 'interface gi1/0/1|int gi1/0/1|interface gigabitethernet 1/0/1|int gigabitethernet 1/0/1|interface gigabitethernet1/0/1|int gigabitethernet1/0/1|interface gi 1/0/1|int gi 1/0/1|interface g1/0/1|int g1/0/1' },
    completed: false,
    points: 10
  },
  {
    id: 'cli-lesson-3-1b',
    order: 13,
    title: { tr: 'Arayüzü Aktifleştir', en: 'Activate Interface' },
    description: { tr: 'no shutdown komutu ile arayüzü aktif hale getirin', en: 'Use no shutdown to activate the interface' },
    hint: { tr: 'SW-Lab: no shutdown yazın', en: 'SW-Lab: Type no shutdown' },
    checkType: 'command',
    checkParams: { commandPattern: 'no shutdown' },
    completed: false,
    points: 10
  },
  {
    id: 'cli-lesson-3-3',
    order: 14,
    title: { tr: 'Port Kapat', en: 'Shutdown Port' },
    description: { tr: 'shutdown komutu ile portu devre dışı bırakın', en: 'Use shutdown to disable the port' },
    hint: { tr: 'SW-Lab: shutdown yazın', en: 'SW-Lab: Type shutdown' },
    checkType: 'command',
    checkParams: { commandPattern: 'shutdown' },
    completed: false,
    points: 10
  },
  {
    id: 'cli-lesson-3-4',
    order: 15,
    title: { tr: 'Arayüz Açıklaması', en: 'Interface Description' },
    description: { tr: 'Arayüze açıklama metni ekleyin', en: 'Add a description to the interface' },
    hint: { tr: 'SW-Lab: description LAN-Port yazın', en: 'SW-Lab: Type description LAN-Port' },
    checkType: 'command',
    checkParams: { commandPattern: 'description' },
    completed: false,
    points: 10
  },
  {
    id: 'cli-lesson-3-5',
    order: 16,
    title: { tr: 'Port Hızı', en: 'Port Speed' },
    description: { tr: 'Arayüz hızını 100 Mbps olarak ayarlayın', en: 'Set interface speed to 100 Mbps' },
    hint: { tr: 'SW-Lab: speed 100 yazın', en: 'SW-Lab: Type speed 100' },
    checkType: 'command',
    checkParams: { commandPattern: 'speed' },
    completed: false,
    points: 10
  },
  {
    id: 'cli-lesson-3-6',
    order: 17,
    title: { tr: 'Port Duplexi', en: 'Port Duplex' },
    description: { tr: 'Arayüz duplex modunu full olarak ayarlayın', en: 'Set interface duplex mode to full' },
    hint: { tr: 'SW-Lab: duplex full yazın', en: 'SW-Lab: Type duplex full' },
    checkType: 'command',
    checkParams: { commandPattern: 'duplex' },
    completed: false,
    points: 10
  },
  // Bölüm 4: VLAN Yönetimi (Switch)
  {
    id: 'cli-lesson-4-1a',
    order: 18,
    sectionTitle: { tr: 'Bölüm 4: VLAN Yönetimi (Switch)', en: 'Section 4: VLAN Management (Switch)' },
    title: { tr: 'VLAN Oluştur', en: 'Create VLAN' },
    description: { tr: 'VLAN 10 oluşturun', en: 'Create VLAN 10' },
    hint: { tr: 'SW-Lab: vlan 10 yazın', en: 'SW-Lab: Type vlan 10' },
    checkType: 'command',
    checkParams: { commandPattern: 'vlan 10' },
    completed: false,
    points: 10
  },
  {
    id: 'cli-lesson-4-1b',
    order: 19,
    title: { tr: 'VLAN İsimlendir', en: 'Name VLAN' },
    description: { tr: 'VLAN\'a SALES ismini verin', en: 'Give the VLAN the name SALES' },
    hint: { tr: 'SW-Lab: name SALES yazın', en: 'SW-Lab: Type name SALES' },
    checkType: 'command',
    checkParams: { commandPattern: 'name SALES' },
    completed: false,
    points: 10
  },
  {
    id: 'cli-lesson-4-exit-vlan',
    order: 20,
    title: { tr: 'VLAN Modundan Çık', en: 'Exit VLAN Mode' },
    description: { tr: 'Arayüz seçimine geçmeden önce VLAN yapılandırma modundan çıkın', en: 'Exit VLAN configuration mode before selecting interfaces' },
    hint: { tr: 'exit', en: 'exit' },
    checkType: 'command',
    checkParams: { commandPattern: 'exit' },
    completed: false,
    points: 5
  },
  {
    id: 'cli-lesson-3-2',
    order: 21,
    title: { tr: 'Arayüz Aralığı', en: 'Interface Range' },
    description: { tr: 'Birden fazla arayüzü aynı anda seçin', en: 'Select multiple interfaces at once' },
    hint: { tr: 'SW-Lab: interface range gi1/0/1 - 5 yazın', en: 'SW-Lab: Type interface range gi1/0/1 - 5' },
    checkType: 'command',
    checkParams: { commandPattern: 'interface range|int range' },
    completed: false,
    points: 15
  },
  {
    id: 'cli-lesson-4-2',
    order: 21,
    title: { tr: 'VLAN Atama', en: 'Assign VLAN' },
    description: { tr: 'Arayüzü VLAN 10\'a atayın', en: 'Assign interface to VLAN 10' },
    hint: { tr: 'SW-Lab: switchport access vlan 10 yazın', en: 'SW-Lab: Type switchport access vlan 10' },
    checkType: 'command',
    checkParams: { commandPattern: 'switchport access vlan 10' },
    completed: false,
    points: 15
  },
  {
    id: 'cli-lesson-4-exit-interface-range',
    order: 22,
    title: { tr: 'Arayüz Modundan Çık', en: 'Exit Interface Mode' },
    description: { tr: 'Trunk yapılandırmasına geçmeden önce arayüz modundan çıkın', en: 'Exit interface mode before configuring the trunk' },
    hint: { tr: 'exit', en: 'exit' },
    checkType: 'command',
    checkParams: { commandPattern: 'exit' },
    completed: false,
    points: 5
  },
  {
    id: 'cli-lesson-4-select-trunk-interface',
    order: 23,
    title: { tr: 'Trunk Arayüzünü Seç', en: 'Select Trunk Interface' },
    description: { tr: 'Trunk ayarları için gi1/0/24 arayüzüne geçin', en: 'Enter interface gi1/0/24 for trunk configuration' },
    hint: { tr: 'SW-Lab: interface gi1/0/24 yazın', en: 'SW-Lab: Type interface gi1/0/24' },
    checkType: 'command',
    checkParams: { commandPattern: 'interface gi1/0/24|int gi1/0/24|interface gigabitethernet 1/0/24|int gigabitethernet 1/0/24|interface gigabitethernet1/0/24|int gigabitethernet1/0/24|interface gi 1/0/24|int gi 1/0/24|interface g1/0/24|int g1/0/24' },
    completed: false,
    points: 5
  },
  {
    id: 'cli-lesson-4-2b',
    order: 24,
    title: { tr: 'Trunk Kapsülleme', en: 'Trunk Encapsulation' },
    description: { tr: 'gi1/0/24 için Trunk kapsülleme protokolünü 802.1Q olarak ayarlayın', en: 'Set trunk encapsulation to 802.1Q for gi1/0/24' },
    hint: { tr: 'SW-Lab: switchport trunk encapsulation dot1q yazın', en: 'SW-Lab: Type switchport trunk encapsulation dot1q' },
    checkType: 'command',
    checkParams: { commandPattern: 'switchport trunk encapsulation' },
    completed: false,
    points: 10
  },
  {
    id: 'cli-lesson-4-3',
    order: 23,
    title: { tr: 'Trunk Portu', en: 'Trunk Port' },
    description: { tr: 'gi1/0/24 için Trunk portu yapılandırın', en: 'Configure trunk port for gi1/0/24' },
    hint: { tr: 'SW-Lab: switchport mode trunk yazın', en: 'SW-Lab: Type switchport mode trunk' },
    checkType: 'command',
    checkParams: { commandPattern: 'switchport mode trunk' },
    completed: false,
    points: 15
  },
  {
    id: 'cli-lesson-4-4',
    order: 24,
    title: { tr: 'Trunk İzinli VLAN', en: 'Trunk Allowed VLAN' },
    description: { tr: 'Trunk üzerinde izinli VLAN\'ları belirleyin', en: 'Set allowed VLANs on trunk' },
    hint: { tr: 'SW-Lab: switchport trunk allowed vlan 10,20 yazın', en: 'SW-Lab: Type switchport trunk allowed vlan 10,20' },
    checkType: 'command',
    checkParams: { commandPattern: 'switchport trunk allowed vlan' },
    completed: false,
    points: 10
  },
  {
    id: 'cli-lesson-4-5',
    order: 25,
    title: { tr: 'Native VLAN', en: 'Native VLAN' },
    description: { tr: 'Trunk için native VLAN ayarlayın', en: 'Set native VLAN for trunk' },
    hint: { tr: 'SW-Lab: switchport trunk native vlan 99 yazın', en: 'SW-Lab: Type switchport trunk native vlan 99' },
    checkType: 'command',
    checkParams: { commandPattern: 'switchport trunk native vlan' },
    completed: false,
    points: 10
  },
  // Bölüm 5: Güvenlik (Switch)
  {
    id: 'cli-lesson-6-1a',
    order: 25,
    sectionTitle: { tr: 'Bölüm 5: Güvenlik (Switch)', en: 'Section 5: Security (Switch)' },
    title: { tr: 'Port Güvenliği', en: 'Port Security' },
    description: { tr: 'gi1/0/1 için Port güvenliğini etkinleştirin', en: 'Enable port security for gi1/0/1' },
    hint: { tr: 'SW-Lab: switchport port-security yazın', en: 'SW-Lab: Type switchport port-security' },
    checkType: 'command',
    checkParams: { commandPattern: 'switchport port-security' },
    completed: false,
    points: 15
  },
  {
    id: 'cli-lesson-6-1b',
    order: 26,
    title: { tr: 'Sticky MAC', en: 'Sticky MAC' },
    description: { tr: 'MAC adreslerini kalıcı öğrenmeyi açın', en: 'Enable sticky MAC learning' },
    hint: { tr: 'SW-Lab: switchport port-security mac-address sticky yazın', en: 'SW-Lab: Type switchport port-security mac-address sticky' },
    checkType: 'command',
    checkParams: { commandPattern: 'mac-address sticky' },
    completed: false,
    points: 15
  },
  {
    id: 'cli-lesson-8-5a',
    order: 27,
    title: { tr: 'DHCP Snooping Aç', en: 'Enable DHCP Snooping' },
    description: { tr: 'DHCP Snooping özelliğini etkinleştirin', en: 'Enable DHCP snooping globally' },
    hint: { tr: 'SW-Lab: ip dhcp snooping yazın', en: 'SW-Lab: Type ip dhcp snooping' },
    checkType: 'command',
    checkParams: { commandPattern: 'ip dhcp snooping' },
    completed: false,
    points: 10
  },
  {
    id: 'cli-lesson-8-5b',
    order: 28,
    title: { tr: 'DHCP Snooping VLAN', en: 'DHCP Snooping VLAN' },
    description: { tr: 'VLAN\'lar için DHCP Snooping yapılandırın', en: 'Configure DHCP snooping for VLANs' },
    hint: { tr: 'SW-Lab: ip dhcp snooping vlan 1,10,20 yazın', en: 'SW-Lab: Type ip dhcp snooping vlan 1,10,20' },
    checkType: 'command',
    checkParams: { commandPattern: 'ip dhcp snooping vlan' },
    completed: false,
    points: 10
  },
  {
    id: 'cli-lesson-6-1c',
    order: 29,
    title: { tr: 'Hata Kurtarma', en: 'Error Recovery' },
    description: { tr: 'errdisable recovery özelliğini etkinleştirin', en: 'Enable errdisable recovery' },
    hint: { tr: 'SW-Lab: errdisable recovery cause all yazın', en: 'SW-Lab: Type errdisable recovery cause all' },
    checkType: 'command',
    checkParams: { commandPattern: 'errdisable recovery' },
    completed: false,
    points: 10
  },
  // Bölüm 6: İleri Switch Konuları
  {
    id: 'cli-lesson-9-2a',
    order: 30,
    sectionTitle: { tr: 'Bölüm 6: İleri Switch Konuları', en: 'Section 6: Advanced Switch Topics' },
    title: { tr: 'GigabitEthernet Arayüz', en: 'GigabitEthernet Interface' },
    description: { tr: 'GigabitEthernet 1/0/1 arayüzüne girin', en: 'Enter GigabitEthernet 1/0/1 interface' },
    hint: { tr: 'SW-Lab: interface gi1/0/1 yazın', en: 'SW-Lab: Type interface gi1/0/1' },
    checkType: 'command',
    checkParams: { commandPattern: 'interface gi1/0/1|int gi1/0/1|interface gigabitethernet 1/0/1|int gigabitethernet 1/0/1|interface gigabitethernet1/0/1|int gigabitethernet1/0/1|interface gi 1/0/1|int gi 1/0/1|interface g1/0/1|int g1/0/1' },
    completed: false,
    points: 10
  },
  {
    id: 'cli-lesson-9-2b',
    order: 31,
    title: { tr: 'EtherChannel', en: 'EtherChannel' },
    description: { tr: 'EtherChannel kanal grubu oluşturun', en: 'Create EtherChannel group' },
    hint: { tr: 'SW-Lab: channel-group 1 mode active yazın', en: 'SW-Lab: Type channel-group 1 mode active' },
    checkType: 'command',
    checkParams: { commandPattern: 'channel-group' },
    completed: false,
    points: 10
  },
  {
    id: 'cli-lesson-9-3a',
    order: 32,
    title: { tr: 'QoS Etkinleştir', en: 'Enable QoS' },
    description: { tr: 'QoS özelliğini etkinleştirin', en: 'Enable QoS globally' },
    hint: { tr: 'SW-Lab: mls qos yazın', en: 'SW-Lab: Type mls qos' },
    checkType: 'command',
    checkParams: { commandPattern: 'mls qos' },
    completed: false,
    points: 10
  },
  {
    id: 'cli-lesson-9-3b',
    order: 33,
    title: { tr: 'QoS Trust', en: 'QoS Trust' },
    description: { tr: 'gi1/0/1 arayüzde CoS güvenini ayarlayın', en: 'Set CoS trust on interface gi1/0/1' },
    hint: { tr: 'SW-Lab: mls qos trust cos yazın', en: 'SW-Lab: Type mls qos trust cos' },
    checkType: 'command',
    checkParams: { commandPattern: 'mls qos trust' },
    completed: false,
    points: 10
  },
  {
    id: 'cli-lesson-9-2c',
    order: 34,
    title: { tr: 'EtherChannel Göster', en: 'Show EtherChannel' },
    description: { tr: 'EtherChannel durumunu görüntüleyin', en: 'Display EtherChannel status' },
    hint: { tr: 'SW-Lab: show etherchannel summary yazın', en: 'SW-Lab: Type show etherchannel summary' },
    checkType: 'command',
    checkParams: { commandPattern: 'show etherchannel summary' },
    completed: false,
    points: 10
  },
  // Bölüm 7: Görüntüleme ve Hata Ayıklama (Switch)
  {
    id: 'cli-lesson-8-2a',
    order: 35,
    sectionTitle: { tr: 'Bölüm 7: Görüntüleme ve Hata Ayıklama (Switch)', en: 'Section 7: Display and Debug Commands (Switch)' },
    title: { tr: 'Arayüzleri Göster', en: 'Show Interfaces' },
    description: { tr: 'show interfaces komutunu kullanın', en: 'Use show interfaces command' },
    hint: { tr: 'SW-Lab: show interfaces yazın', en: 'SW-Lab: Type show interfaces' },
    checkType: 'command',
    checkParams: { commandPattern: 'show interfaces' },
    completed: false,
    points: 10
  },
  {
    id: 'cli-lesson-8-2c',
    order: 36,
    title: { tr: 'VLAN\'ları Göster', en: 'Show VLANs' },
    description: { tr: 'show vlan komutunu kullanın', en: 'Use show vlan command' },
    hint: { tr: 'SW-Lab: show vlan yazın', en: 'SW-Lab: Type show vlan' },
    checkType: 'command',
    checkParams: { commandPattern: 'show vlan' },
    completed: false,
    points: 10
  },
  {
    id: 'cli-lesson-8-3a',
    order: 37,
    title: { tr: 'STP Göster', en: 'Show STP' },
    description: { tr: 'show spanning-tree komutunu kullanın', en: 'Use show spanning-tree command' },
    hint: { tr: 'SW-Lab: show spanning-tree yazın', en: 'SW-Lab: Type show spanning-tree' },
    checkType: 'command',
    checkParams: { commandPattern: 'show spanning-tree' },
    completed: false,
    points: 15
  },
  {
    id: 'cli-lesson-8-3b',
    order: 38,
    title: { tr: 'STP Modu Ayarla', en: 'Set STP Mode' },
    description: { tr: 'spanning-tree mode komutunu kullanın', en: 'Use spanning-tree mode command' },
    hint: { tr: 'SW-Lab: spanning-tree mode rapid-pvst yazın', en: 'SW-Lab: Type spanning-tree mode rapid-pvst' },
    checkType: 'command',
    checkParams: { commandPattern: 'spanning-tree mode' },
    completed: false,
    points: 15
  },
  {
    id: 'cli-lesson-8-4a',
    order: 39,
    title: { tr: 'CDP Komşuları Göster', en: 'Show CDP Neighbors' },
    description: { tr: 'show cdp neighbors komutunu kullanın', en: 'Use show cdp neighbors command' },
    hint: { tr: 'SW-Lab: show cdp neighbors yazın', en: 'SW-Lab: Type show cdp neighbors' },
    checkType: 'command',
    checkParams: { commandPattern: 'show cdp neighbors' },
    completed: false,
    points: 15
  },
  {
    id: 'cli-lesson-8-4b',
    order: 40,
    title: { tr: 'CDP Aç', en: 'Enable CDP' },
    description: { tr: 'cdp run komutunu kullanın', en: 'Use cdp run command' },
    hint: { tr: 'SW-Lab: cdp run yazın', en: 'SW-Lab: Type cdp run' },
    checkType: 'command',
    checkParams: { commandPattern: 'cdp run' },
    completed: false,
    points: 15
  },
  {
    id: 'cli-lesson-9-5a',
    order: 41,
    title: { tr: 'Envanter Göster', en: 'Show Inventory' },
    description: { tr: 'show inventory komutunu kullanın', en: 'Use show inventory command' },
    hint: { tr: 'SW-Lab: show inventory yazın', en: 'SW-Lab: Type show inventory' },
    checkType: 'command',
    checkParams: { commandPattern: 'show inventory' },
    completed: false,
    points: 10
  },
  {
    id: 'cli-lesson-9-5b',
    order: 42,
    title: { tr: 'Ortam Göster', en: 'Show Environment' },
    description: { tr: 'show environment komutunu kullanın', en: 'Use show environment command' },
    hint: { tr: 'SW-Lab: show environment yazın', en: 'SW-Lab: Type show environment' },
    checkType: 'command',
    checkParams: { commandPattern: 'show environment' },
    completed: false,
    points: 10
  },
  {
    id: 'cli-lesson-9-5c',
    order: 43,
    title: { tr: 'Bellek Göster', en: 'Show Memory' },
    description: { tr: 'show memory komutunu kullanın', en: 'Use show memory command' },
    hint: { tr: 'SW-Lab: show memory yazın', en: 'SW-Lab: Type show memory' },
    checkType: 'command',
    checkParams: { commandPattern: 'show memory' },
    completed: false,
    points: 10
  },
  {
    id: 'cli-lesson-8-5c',
    order: 44,
    title: { tr: 'MAC Tablosu Göster', en: 'Show MAC Table' },
    description: { tr: 'show mac address-table komutunu kullanın', en: 'Use show mac address-table command' },
    hint: { tr: 'SW-Lab: show mac address-table yazın', en: 'SW-Lab: Type show mac address-table' },
    checkType: 'command',
    checkParams: { commandPattern: 'show mac address-table' },
    completed: false,
    points: 10
  },
  {
    id: 'cli-lesson-8-2d',
    order: 45,
    title: { tr: 'VLAN Özeti Göster', en: 'Show VLAN Brief' },
    description: { tr: 'show vlan brief komutunu kullanın', en: 'Use show vlan brief command' },
    hint: { tr: 'SW-Lab: show vlan brief yazın', en: 'SW-Lab: Type show vlan brief' },
    checkType: 'command',
    checkParams: { commandPattern: 'show vlan brief' },
    completed: false,
    points: 10
  },
  {
    id: 'cli-lesson-8-2e',
    order: 46,
    title: { tr: 'Trunk\'ları Göster', en: 'Show Trunk' },
    description: { tr: 'show interfaces trunk komutunu kullanın', en: 'Use show interfaces trunk command' },
    hint: { tr: 'SW-Lab: show interfaces trunk yazın', en: 'SW-Lab: Type show interfaces trunk' },
    checkType: 'command',
    checkParams: { commandPattern: 'show interfaces trunk' },
    completed: false,
    points: 10
  },
  {
    id: 'cli-lesson-8-5d',
    order: 47,
    title: { tr: 'Port Güvenliği Göster', en: 'Show Port Security' },
    description: { tr: 'show port-security komutunu kullanın', en: 'Use show port-security command' },
    hint: { tr: 'SW-Lab: show port-security yazın', en: 'SW-Lab: Type show port-security' },
    checkType: 'command',
    checkParams: { commandPattern: 'show port-security' },
    completed: false,
    points: 10
  },
  {
    id: 'cli-lesson-8-4c',
    order: 48,
    title: { tr: 'CDP Komşuları Detay', en: 'Show CDP Details' },
    description: { tr: 'CDP komşu detaylarını görüntüleyin', en: 'Display CDP neighbor details' },
    hint: { tr: 'SW-Lab: show cdp neighbors detail yazın', en: 'SW-Lab: Type show cdp neighbors detail' },
    checkType: 'command',
    checkParams: { commandPattern: 'show cdp neighbors detail' },
    completed: false,
    points: 10
  },
  {
    id: 'cli-lesson-8-4d',
    order: 49,
    title: { tr: 'LLDP Komşuları Göster', en: 'Show LLDP Neighbors' },
    description: { tr: 'show lldp neighbors komutunu kullanın', en: 'Use show lldp neighbors command' },
    hint: { tr: 'SW-Lab: show lldp neighbors yazın', en: 'SW-Lab: Type show lldp neighbors' },
    checkType: 'command',
    checkParams: { commandPattern: 'show lldp neighbors' },
    completed: false,
    points: 10
  },
  {
    id: 'cli-lesson-9-5d',
    order: 50,
    title: { tr: 'Sürüm Göster', en: 'Show Version' },
    description: { tr: 'show version komutunu kullanın', en: 'Use show version command' },
    hint: { tr: 'SW-Lab: show version yazın', en: 'SW-Lab: Type show version' },
    checkType: 'command',
    checkParams: { commandPattern: 'show version' },
    completed: false,
    points: 10
  },
  {
    id: 'cli-lesson-9-5e',
    order: 51,
    title: { tr: 'Saat Göster', en: 'Show Clock' },
    description: { tr: 'show clock komutunu kullanın', en: 'Use show clock command' },
    hint: { tr: 'SW-Lab: show clock yazın', en: 'SW-Lab: Type show clock' },
    checkType: 'command',
    checkParams: { commandPattern: 'show clock' },
    completed: false,
    points: 10
  },
  {
    id: 'cli-lesson-9-5f',
    order: 52,
    title: { tr: 'Komut Geçmişi Göster', en: 'Show History' },
    description: { tr: 'show history komutunu kullanın', en: 'Use show history command' },
    hint: { tr: 'SW-Lab: show history yazın', en: 'SW-Lab: Type show history' },
    checkType: 'command',
    checkParams: { commandPattern: 'show history' },
    completed: false,
    points: 10
  }
];