import { Terminal, Globe, Wifi, Settings, Eye, Server, Router, Network, Book, Zap, Keyboard, LucideIcon, Lightbulb, FileText, Layers, Shield, Cpu, Radio } from 'lucide-react';

export interface CommandDefinition {
  id: string;
  icon: LucideIcon;
  title: string;
  cmds: [string, string, string?][];
  type?: 'commands' | 'info' | 'examples';
}

export function getCommandCategories(isTR: boolean): CommandDefinition[] {
  return [
    {
      id: 'system',
      icon: Terminal,
      title: isTR ? 'Oturum' : 'Session',
      type: 'commands',
      cmds: [
        ['enable', isTR ? 'Ayr─▒cal─▒kl─▒ moda ge├ğ' : 'Enter privileged mode', '>'],
        ['disable', isTR ? 'Kullan─▒c─▒ moduna d├Ân' : 'Return to user mode', '#'],
        ['configure terminal', isTR ? 'Yap─▒land─▒rma modu' : 'Enter config mode', '#'],
        ['exit', isTR ? 'Moddan ├ğ─▒k' : 'Exit current mode'],
        ['end', isTR ? 'Ayr─▒cal─▒kl─▒ moda d├Ân' : 'Return to privileged mode'],
        ['help', isTR ? 'Yard─▒m sistemini g├Âster' : 'Display help system'],
      ]
    },
    {
      id: 'privileged',
      icon: Server,
      title: isTR ? 'Privileged EXEC' : 'Privileged EXEC',
      type: 'commands',
      cmds: [
        ['ping <host> [s] [c]', isTR ? 'Ba─şlant─▒ testi (ICMP)' : 'Ping host (ICMP)', '#'],
        ['traceroute <host>', isTR ? 'Rota izleme' : 'Trace route', '#'],
        ['clock set <hh:mm:ss> <day> <month> <year>', isTR ? 'Sistem saatini ayarla' : 'Set system clock', '#'],
        ['telnet <host> [port]', isTR ? 'Telnet ba─şlant─▒s─▒' : 'Telnet connection', '#'],
        ['ssh [-l user] <host>', isTR ? 'SSH ba─şlant─▒s─▒' : 'SSH connection', '#'],
        ['write memory', isTR ? 'Yap─▒land─▒rmay─▒ kaydet' : 'Save configuration', '#'],
        ['copy running-config startup-config', isTR ? 'Yap─▒land─▒rmay─▒ kaydet' : 'Save config', '#'],
        ['copy running-config flash:', isTR ? 'Flash\'a kaydet' : 'Save to flash', '#'],
        ['copy flash: startup-config', isTR ? 'Flash\'tan geri y├╝kle' : 'Restore from flash', '#'],
        ['delete flash:vlan.dat', isTR ? 'VLAN veritaban─▒ sil' : 'Delete VLAN database', '#'],
        ['erase startup-config', isTR ? 'Startup config sil' : 'Erase startup config', '#'],
        ['erase nvram', isTR ? 'NVRAM dosya sistemini sil' : 'Erase NVRAM', '#'],
        ['reload', isTR ? 'Cihaz─▒ yeniden y├╝kle' : 'Reload device', '#'],
        ['ip route <n> <mask> <h>', isTR ? 'Statik rota ekle' : 'Add static route', '#'],
        ['no ip route <n> <mask> <h>', isTR ? 'Statik rotay─▒ sil' : 'Remove static route', '#'],
        ['debug <type>', isTR ? 'Hata ay─▒klamay─▒ a├ğ' : 'Enable debugging', '#'],
        ['undebug all', isTR ? 'T├╝m hatalar─▒ kapat' : 'Disable all debugging', '#'],
        ['terminal length <0-512>', isTR ? 'Terminal sat─▒r uzunlu─şu' : 'Set terminal length', '#'],
        ['clear arp-cache', isTR ? 'ARP ├Ânbelle─şini sil' : 'Clear ARP cache', '#'],
        ['clear mac address-table', isTR ? 'MAC tablosunu sil' : 'Clear MAC table', '#'],
        ['clear counters', isTR ? 'Saya├ğlar─▒ s─▒f─▒rla' : 'Clear counters', '#'],
        ['do <command>', isTR ? 'Ayr─▒cal─▒kl─▒ komut ├ğal─▒┼şt─▒r' : 'Execute privileged command', '(config)#'],
        ['ftp <host>', isTR ? 'FTP ba─şlant─▒s─▒' : 'FTP connection', '#'],
        ['mail <recipient>', isTR ? 'E-posta g├Ânder' : 'Send email', '#'],
        ['more <file>', isTR ? 'Dosya i├ğeri─şini g├Âster' : 'Display file contents', '#'],
        ['setup', isTR ? 'Kurulum sihirbaz─▒' : 'Setup wizard', '#'],
        ['test', isTR ? 'Tan─▒lama testi' : 'Diagnostic test', '#'],
        ['disconnect <session>', isTR ? 'Oturumu kes' : 'Disconnect session', '#'],
        ['resume <session>', isTR ? 'Oturuma devam et' : 'Resume session', '#'],
        ['suspend', isTR ? 'Oturumu ask─▒ya al' : 'Suspend session', '#'],
        ['copy running-config tftp:', isTR ? 'TFTP\'ye yap─▒land─▒rma g├Ânder' : 'Copy config to TFTP', '#'],
        ['copy tftp: running-config', isTR ? 'TFTP\'den yap─▒land─▒rma al' : 'Restore config from TFTP', '#'],
        ['copy startup-config running-config', isTR ? 'Startup config\'u ├ğal─▒┼şt─▒r' : 'Merge startup to running', '#'],
        ['copy tftp: flash:', isTR ? 'TFTP\'den IOS y├╝kle' : 'Copy IOS from TFTP', '#'],
        ['clear line <n>', isTR ? 'Hatt─▒ s─▒f─▒rla' : 'Clear line', '#'],
        ['clear interface <type/n>', isTR ? 'Aray├╝z saya├ğlar─▒n─▒ s─▒f─▒rla' : 'Clear interface counters', '#'],
        ['terminal monitor', isTR ? 'Log mesajlar─▒n─▒ g├Âr├╝nt├╝le' : 'Monitor log messages', '#'],
        ['terminal no monitor', isTR ? 'Log g├Âr├╝nt├╝lemeyi kapat' : 'Stop monitoring logs', '#'],
        ['terminal width <n>', isTR ? 'Terminal geni┼şli─şi' : 'Set terminal width', '#'],
      ]
    },
    {
      id: 'global',
      icon: Globe,
      title: isTR ? 'Global Yap─▒land─▒rma' : 'Global Config',
      type: 'commands',
      cmds: [
        ['hostname <name>', isTR ? 'Cihaz ad─▒' : 'Set hostname', '(config)#'],
        ['vlan <id>', isTR ? 'VLAN olu┼ştur' : 'Create VLAN', '(config)#'],
        ['no vlan <id>', isTR ? 'VLAN sil' : 'Delete VLAN', '(config)#'],
        ['name <name>', isTR ? 'VLAN ad─▒ (vlan modunda)' : 'Set VLAN name', '(config-vlan)#'],
        ['interface <name>', isTR ? 'Aray├╝z se├ğ' : 'Select interface', '(config)#'],
        ['interface range <r>', isTR ? 'Aray├╝z aral─▒─ş─▒' : 'Interface range', '(config)#'],
        ['no interface vlan <id>', isTR ? 'VLAN aray├╝z├╝n├╝ sil' : 'Delete VLAN interface', '(config)#'],
        ['ip routing', isTR ? 'IP y├Ânlendirme (L3)' : 'Enable IP routing (L3)', '(config)#'],
        ['no ip routing', isTR ? 'IP y├Ânlendirmeyi kapat' : 'Disable IP routing', '(config)#'],
        ['ip default-gateway <ip>', isTR ? 'Varsay─▒lan a─ş ge├ğidi' : 'Set default gateway', '(config)#'],
        ['ip domain-name <name>', isTR ? 'Alan ad─▒' : 'Set domain name', '(config)#'],
        ['no ip domain lookup', isTR ? 'DNS aramay─▒ kapat' : 'Disable DNS lookup', '(config)#'],
        ['ip http server', isTR ? 'HTTP sunucusunu a├ğ' : 'Enable HTTP server', '(config)#'],
        ['no ip http server', isTR ? 'HTTP sunucusunu kapat' : 'Disable HTTP server', '(config)#'],
        ['ip ssh version {1|2}', isTR ? 'SSH versiyonu' : 'Set SSH version', '(config)#'],
        ['ip ssh time-out <s>', isTR ? 'SSH zaman a┼ş─▒m─▒' : 'Set SSH timeout', '(config)#'],
        ['ip ssh authentication-retries <n>', isTR ? 'SSH deneme say─▒s─▒' : 'SSH retry limit', '(config)#'],
        ['ip dhcp snooping', isTR ? 'DHCP snooping a├ğ' : 'Enable DHCP snooping', '(config)#'],
        ['ip dhcp snooping vlan <ids>', isTR ? 'VLANlarda DHCP snooping' : 'DHCP snooping on VLANs', '(config)#'],
        ['service password-enc', isTR ? 'Parolalar─▒ ┼şifrele' : 'Encrypt passwords', '(config)#'],
        ['enable secret <pass>', isTR ? 'Enable secret parolas─▒' : 'Set enable secret', '(config)#'],
        ['enable password <pass>', isTR ? 'Enable password parolas─▒' : 'Set enable password', '(config)#'],
        ['banner motd #<msg>#', isTR ? 'MOTD banner' : 'MOTD banner', '(config)#'],
        ['banner login #<msg>#', isTR ? 'Login banner' : 'Login banner', '(config)#'],
        ['no banner {motd|login}', isTR ? 'Banner sil' : 'Remove banner', '(config)#'],
        ['vtp mode {server|client}', isTR ? 'VTP modu' : 'Set VTP mode', '(config)#'],
        ['vtp domain <name>', isTR ? 'VTP etki alan─▒' : 'Set VTP domain', '(config)#'],
        ['vtp password <pass>', isTR ? 'VTP parolas─▒' : 'Set VTP password', '(config)#'],
        ['spanning-tree mode {m}', isTR ? 'STP modu' : 'Set STP mode', '(config)#'],
        ['spanning-tree vlan <id> priority <val>', isTR ? 'VLAN STP ├Ânceli─şi' : 'VLAN STP priority', '(config)#'],
        ['spanning-tree vlan <id> root', isTR ? 'VLAN STP root' : 'VLAN STP root', '(config)#'],
        ['no spanning-tree', isTR ? 'STP\'yi kapat' : 'Disable spanning-tree', '(config)#'],
        ['username <n> pass <p>', isTR ? 'Kullan─▒c─▒ olu┼ştur' : 'Create user', '(config)#'],
        ['no username <name>', isTR ? 'Kullan─▒c─▒y─▒ sil' : 'Remove user', '(config)#'],
        ['cdp run', isTR ? 'CDP\'yi a├ğ' : 'Enable CDP globally', '(config)#'],
        ['mls qos', isTR ? 'QoS\'u a├ğ' : 'Enable MLS QoS', '(config)#'],
        ['ip dhcp pool <name>', isTR ? 'DHCP havuzu' : 'Create DHCP pool', '(config)#'],
        ['no ip dhcp pool <name>', isTR ? 'DHCP havuzunu sil' : 'Remove DHCP pool', '(config)#'],
        ['ip dhcp excluded <ip>', isTR ? 'DHCP hari├ğ tut' : 'Exclude DHCP addr', '(config)#'],
        ['ip nat pool <n> <s-e> <m>', isTR ? 'NAT havuzu tan─▒mla' : 'Define NAT pool', '(config)#'],
        ['ip nat inside source <rule>', isTR ? 'NAT kural─▒ ekle' : 'Add NAT rule', '(config)#'],
        ['ntp server <ip>', isTR ? 'NTP sunucusu' : 'Set NTP server', '(config)#'],
        ['clock timezone <n> <o>', isTR ? 'Zaman dilimi' : 'Set timezone', '(config)#'],
        ['ip name-server <ip>', isTR ? 'DNS sunucusu' : 'Set DNS server', '(config)#'],
        ['system mtu <size>', isTR ? 'Sistem MTU' : 'Set system MTU', '(config)#'],
        ['errdisable recovery', isTR ? 'Hata kurtarma' : 'Errdisable recovery', '(config)#'],
        ['spanning-tree portfast default', isTR ? 'Global PortFast' : 'Global PortFast', '(config)#'],
        ['ipv6 unicast-routing', isTR ? 'IPv6 y├Ânlendirme' : 'Enable IPv6 routing', '(config)#'],
        ['crypto key generate rsa', isTR ? 'RSA anahtar─▒ ├╝ret (SSH)' : 'Generate RSA keys', '(config)#'],
        ['snmp-server community <c>', isTR ? 'SNMP toplulu─şu' : 'Set SNMP community', '(config)#'],
        ['archive', isTR ? 'Ar┼şiv yap─▒land─▒rmas─▒' : 'Archive configuration', '(config)#'],
        ['alias <mode> <n> <c>', isTR ? 'Komut takma ad─▒' : 'Command alias', '(config)#'],
        ['macro name <name>', isTR ? 'Komut makrosu' : 'Define command macro', '(config)#'],
        ['sdm prefer <template>', isTR ? 'SDM ┼şablonu' : 'Set SDM template', '(config)#'],
        ['ip arp inspection vlan <id>', isTR ? 'DAI (ARP Denetimi)' : 'Enable DAI on VLAN', '(config)#'],
      ]
    },
    {
      id: 'examples-dhcp',
      icon: Lightbulb,
      title: isTR ? '├ûrnek: DHCP Sunucusu' : 'Example: DHCP Server',
      type: 'examples',
      cmds: [
        ['ip dhcp pool MY_POOL', isTR ? '1. DHCP havuzu olu┼ştur' : '1. Create DHCP pool', '(config)#'],
        ['network 192.168.1.0 255.255.255.0', isTR ? '2. Havuz a─ş─▒n─▒ ve maskesini belirle' : '2. Define pool network and mask', '(config-dhcp)#'],
        ['default-router 192.168.1.1', isTR ? '3. Varsay─▒lan a─ş ge├ğidini belirle' : '3. Set default gateway', '(config-dhcp)#'],
        ['dns-server 8.8.8.8', isTR ? '4. DNS sunucusunu belirle' : '4. Set DNS server', '(config-dhcp)#'],
        ['exit', isTR ? '5. Havuz modundan ├ğ─▒k' : '5. Exit pool mode', '(config-dhcp)#'],
        ['ip dhcp excluded-address 192.168.1.1', isTR ? '6. Da─ş─▒t─▒lmayacak adresleri hari├ğ tut' : '6. Exclude addresses from pool', '(config)#'],
      ]
    },
    {
      id: 'examples-wifi',
      icon: Wifi,
      title: isTR ? '├ûrnek: Wi-Fi Ayarlar─▒' : 'Example: Wi-Fi Setup',
      type: 'examples',
      cmds: [
        ['dot11 ssid MY_WIFI', isTR ? '1. SSID yap─▒land─▒rmas─▒na gir' : '1. Enter SSID config', '(config)#'],
        ['authentication open', isTR ? '2. A├ğ─▒k kimlik do─şrulama (veya WPA)' : '2. Open authentication (or WPA)', '(config-ssid)#'],
        ['guest-mode', isTR ? '3. SSID\'yi yay─▒nla (Beacon)' : '3. Broadcast SSID (Beacon)', '(config-ssid)#'],
        ['exit', isTR ? '4. SSID modundan ├ğ─▒k' : '4. Exit SSID mode', '(config-ssid)#'],
        ['interface Dot11Radio 0', isTR ? '5. Radyo aray├╝z├╝ne gir' : '5. Enter radio interface', '(config)#'],
        ['ssid MY_WIFI', isTR ? '6. SSID\'yi radyoya ata' : '6. Assign SSID to radio', '(config-if)#'],
        ['no shutdown', isTR ? '7. Radyoyu etkinle┼ştir' : '7. Enable radio', '(config-if)#'],
      ]
    },
    {
      id: 'examples-vlan',
      icon: Layers,
      title: isTR ? '├ûrnek: VLAN & Trunk' : 'Example: VLAN & Trunk',
      type: 'examples',
      cmds: [
        ['vlan 10', isTR ? '1. VLAN 10 olu┼ştur' : '1. Create VLAN 10', '(config)#'],
        ['name SALES', isTR ? '2. VLAN ad─▒n─▒ "SALES" yap' : '2. Name VLAN "SALES"', '(config-vlan)#'],
        ['interface range fa0/1 - 10', isTR ? '3. ─░lk 10 portu se├ğ' : '3. Select first 10 ports', '(config)#'],
        ['switchport mode access', isTR ? '4. Portlar─▒ eri┼şim moduna al' : '4. Set ports to access mode', '(config-if)#'],
        ['switchport access vlan 10', isTR ? '5. Portlar─▒ VLAN 10\'a ata' : '5. Assign ports to VLAN 10', '(config-if)#'],
        ['interface gi0/1', isTR ? '6. Uplink portunu se├ğ' : '6. Select uplink port', '(config)#'],
        ['switchport mode trunk', isTR ? '7. Portu Trunk moduna al' : '7. Set port to Trunk mode', '(config-if)#'],
      ]
    },
    {
      id: 'knowledge-stp',
      icon: Book,
      title: isTR ? 'Bilgi: STP Nedir?' : 'Knowledge: What is STP?',
      type: 'info',
      cmds: [
        ['Spanning Tree Protocol', isTR ? 'STP (Spanning Tree Protocol), yerel a─şlarda (LAN) fiziksel d├Âng├╝leri (loop) ├Ânlemek i├ğin kullan─▒lan bir Layer 2 protokol├╝d├╝r. E─şer a─şda yedekli ba─şlant─▒lar varsa ve STP yoksa, paketler sonsuz bir d├Âng├╝ye girerek a─ş─▒ kilitleyebilir (Broadcast Storm). STP, baz─▒ portlar─▒ bloklayarak d├Âng├╝s├╝z bir yap─▒ olu┼şturur.' : 'STP (Spanning Tree Protocol) is a Layer 2 protocol used to prevent physical loops in local area networks (LANs). If there are redundant links in a network without STP, packets can enter an infinite loop, crashing the network (Broadcast Storm). STP creates a loop-free topology by blocking certain ports.'],
      ]
    },
    {
      id: 'knowledge-dhcp',
      icon: FileText,
      title: isTR ? 'Bilgi: DHCP Nedir?' : 'Knowledge: What is DHCP?',
      type: 'info',
      cmds: [
        ['Dynamic Host Configuration Protocol', isTR ? 'DHCP, a─şdaki cihazlara otomatik olarak IP adresi, alt a─ş maskesi, varsay─▒lan a─ş ge├ğidi ve DNS gibi yap─▒land─▒rma bilgilerini da─ş─▒tan bir protokold├╝r. Bu sayede her cihaz─▒ manuel olarak yap─▒land─▒rma zahmeti ortadan kalkar ve IP ├ğak─▒┼şmalar─▒ ├Ânlenir.' : 'DHCP is a protocol that automatically assigns IP addresses, subnet masks, default gateways, and DNS information to devices on a network. This eliminates the need for manual configuration of each device and helps prevent IP address conflicts.'],
      ]
    },
    {
      id: 'knowledge-vlan',
      icon: Network,
      title: isTR ? 'Bilgi: VLAN Nedir?' : 'Knowledge: What is VLAN?',
      type: 'info',
      cmds: [
        ['Virtual Local Area Network', isTR ? 'VLAN, fiziksel bir yerel a─ş─▒ mant─▒ksal olarak daha k├╝├ğ├╝k par├ğalara b├Âlen teknolojidir. Ayn─▒ switch ├╝zerindeki kullan─▒c─▒lar─▒ farkl─▒ VLAN\'lara ay─▒rarak g├╝venli─şi art─▒rabilir ve a─ş trafi─şini (broadcast) optimize edebilirsiniz. Farkl─▒ VLAN\'lar aras─▒ndaki ileti┼şim i├ğin bir Router veya L3 Switch gerekir.' : 'VLAN is a technology that logically partitions a physical LAN into smaller segments. By placing users on the same switch into different VLANs, you can improve security and optimize network traffic (broadcast). Communication between different VLANs requires a Router or L3 Switch.'],
      ]
    },
    {
      id: 'iot',
      icon: Cpu,
      title: isTR ? 'IoT (Nesnelerin ─░nterneti)' : 'IoT (Internet of Things)',
      type: 'commands',
      cmds: [
        ['iot sensor <name>', isTR ? 'IoT sens├Âr/servis tan─▒mla (├Âr: lamp, cooler, heater, motion, smoke, servo, gas, temp, distance, ldr, rain, rfid, pir)' : 'Define IoT sensor/service (e.g. lamp, cooler, heater, motion, smoke, servo, gas, temp, distance, ldr, rain, rfid, pir)', '(config)#'],
        ['no iot sensor <name>', isTR ? 'IoT sens├Âr├╝n├╝ sil' : 'Remove IoT sensor', '(config)#'],
        ['iot name <name>', isTR ? 'IoT cihaz─▒na isim ver' : 'Name the IoT device', '(config)#'],
        ['iot wifi <ssid>', isTR ? 'IoT\'yi Wi-Fi a─ş─▒na ba─şla' : 'Connect IoT to Wi-Fi network', '(config)#'],
        ['no iot wifi', isTR ? 'IoT Wi-Fi ba─şlant─▒s─▒n─▒ kes' : 'Disconnect IoT from Wi-Fi', '(config)#'],
        ['show iot sensors', isTR ? 'IoT sens├Ârlerini listele' : 'List IoT sensors', '#'],
        ['show iot status', isTR ? 'IoT cihaz durumunu g├Âster' : 'Show IoT device status', '#'],
      ]
    },
    {
      id: 'firewall',
      icon: Shield,
      title: isTR ? 'G├╝venlik Duvar─▒ (ASA/Firewall)' : 'Firewall (ASA)',
      type: 'commands',
      cmds: [
        ['nameif <name>', isTR ? 'Aray├╝z ad─▒n─▒ belirle' : 'Set interface name', '(config-if)#'],
        ['no nameif', isTR ? 'Aray├╝z ad─▒n─▒ sil' : 'Remove interface name', '(config-if)#'],
        ['security-level <0-100>', isTR ? 'G├╝venlik seviyesi ata' : 'Set security level', '(config-if)#'],
        ['ip access-group <id> {in|out}', isTR ? 'ACL\'yi aray├╝ze uygula' : 'Apply ACL to interface', '(config-if)#'],
        ['show nameif', isTR ? 'Aray├╝z adlar─▒n─▒ g├Âster' : 'Show interface names', '#'],
        ['show ip access-group', isTR ? 'ACL uygulamalar─▒n─▒ g├Âster' : 'Show applied ACLs', '#'],
      ]
    },
    {
      id: 'wlc',
      icon: Radio,
      title: isTR ? 'WLC / AP Y├Ânetimi' : 'WLC / AP Management',
      type: 'commands',
      cmds: [
        ['ap name <name>', isTR ? 'Access Point adland─▒r' : 'Name the Access Point', '(config)#'],
        ['ap auth-mac <mac>', isTR ? 'AP MAC adres yetkilendirmesi' : 'AP MAC address authorization', '(config)#'],
        ['ap rf-channel <num>', isTR ? 'AP RF kanal─▒n─▒ ayarla' : 'Set AP RF channel', '(config)#'],
        ['show ap summary', isTR ? 'AP ├Âzetini g├Âster' : 'Show AP summary', '#'],
        ['show ap config [name]', isTR ? 'AP yap─▒land─▒rmas─▒n─▒ g├Âster' : 'Show AP configuration', '#'],
        ['show ap join statistics [name]', isTR ? 'AP kat─▒l─▒m istatistiklerini g├Âster' : 'Show AP join statistics', '#'],
        ['show wlan summary', isTR ? 'WLAN ├Âzetini g├Âster' : 'Show WLAN summary', '#'],
        ['show wlan <id>', isTR ? 'WLAN detaylar─▒n─▒ g├Âster' : 'Show WLAN details', '#'],
      ]
    },
    {
      id: 'interface',
      icon: Settings,
      title: isTR ? 'Aray├╝z Yap─▒land─▒rmas─▒' : 'Interface Config',
      type: 'commands',
      cmds: [
        ['shutdown', isTR ? 'Aray├╝z├╝ kapat' : 'Disable interface', '(config-if)#'],
        ['no shutdown', isTR ? 'Aray├╝z├╝ a├ğ' : 'Enable interface', '(config-if)#'],
        ['speed {10|100|1000|10000|auto}', isTR ? 'H─▒z ayarla' : 'Set speed', '(config-if)#'],
        ['duplex {half|full|auto}', isTR ? 'Duplex ayarla' : 'Set duplex', '(config-if)#'],
        ['description <text>', isTR ? 'Aray├╝z a├ğ─▒klamas─▒' : 'Set description', '(config-if)#'],
        ['no description', isTR ? 'A├ğ─▒klamay─▒ sil' : 'Clear description', '(config-if)#'],
        ['switchport mode access', isTR ? 'Eri┼şim modu' : 'Access mode', '(config-if)#'],
        ['switchport mode trunk', isTR ? 'Trunk modu' : 'Trunk mode', '(config-if)#'],
        ['switchport trunk encapsulation dot1q', isTR ? 'Trunk kaps├╝lleme' : 'Trunk encapsulation', '(config-if)#'],
        ['encapsulation dot1q <vlan>', isTR ? 'Subinterface VLAN─▒' : 'Subinterface VLAN', '(config-subif)#'],
        ['switchport mode dynamic {m}', isTR ? 'DTP modu' : 'Set DTP mode', '(config-if)#'],
        ['switchport mode dot1q-tunnel', isTR ? 'Dot1q tunnel' : 'Dot1q tunnel mode', '(config-if)#'],
        ['no switchport mode', isTR ? 'Modu s─▒f─▒rla' : 'Reset switchport mode', '(config-if)#'],
        ['switchport access vlan <id>', isTR ? 'VLAN ata' : 'Assign VLAN', '(config-if)#'],
        ['no switchport access vlan', isTR ? 'VLAN atamas─▒n─▒ sil' : 'Remove VLAN assign', '(config-if)#'],
        ['switchport trunk native <id>', isTR ? 'Native VLAN' : 'Set native VLAN', '(config-if)#'],
        ['switchport trunk allowed <l>', isTR ? '─░zinli VLANlar' : 'Set allowed VLANs', '(config-if)#'],
        ['switchport nonegotiate', isTR ? 'DTP\'yi kapat' : 'Disable DTP', '(config-if)#'],
        ['switchport voice vlan <id>', isTR ? 'Ses VLAN\'─▒' : 'Set voice VLAN', '(config-if)#'],
        ['switchport port-security', isTR ? 'Port g├╝venli─şi' : 'Port security', '(config-if)#'],
        ['switchport port-security max <n>', isTR ? 'Maksimum MAC' : 'Set max MACs', '(config-if)#'],
        ['switchport port-security violation {a}', isTR ? '─░hlal aksiyonu' : 'Violation action', '(config-if)#'],
        ['switchport port-security sticky', isTR ? 'Sticky MAC' : 'Enable sticky MAC', '(config-if)#'],
        ['switchport port-security aging time <n>', isTR ? 'G├╝venlik ya┼şlanma s├╝resi' : 'Port-security aging time', '(config-if)#'],
        ['no switchport port-security', isTR ? 'G├╝venli─şi kapat' : 'Disable port security', '(config-if)#'],
        ['switchport protected', isTR ? 'Korumal─▒ port' : 'Protected port', '(config-if)#'],
        ['switchport block {unicast|multicast}', isTR ? 'Trafik bloklama' : 'Block traffic', '(config-if)#'],
        ['no switchport', isTR ? 'L3 portuna d├Ân├╝┼şt├╝r' : 'Convert to L3 port', '(config-if)#'],
        ['spanning-tree portfast', isTR ? 'PortFast a├ğ' : 'Enable PortFast', '(config-if)#'],
        ['spanning-tree bpduguard {e|d}', isTR ? 'BPDU Guard' : 'BPDU Guard', '(config-if)#'],
        ['spanning-tree cost <cost>', isTR ? 'STP maliyeti' : 'Set STP cost', '(config-if)#'],
        ['spanning-tree priority <p>', isTR ? 'STP ├Ânceli─şi' : 'Set STP priority', '(config-if)#'],
        ['ip address <ip> <mask>', isTR ? 'IP adresi ata' : 'Set IP address', '(config-if)#'],
        ['ipv6 address <ip>/<p>', isTR ? 'IPv6 adresi ata' : 'Set IPv6 address', '(config-if)#'],
        ['no ip address', isTR ? 'IP adresini sil' : 'Remove IP address', '(config-if)#'],
        ['ip default-gateway <ip>', isTR ? 'Aray├╝z gateway' : 'Interface gateway', '(config-if)#'],
        ['no ip default-gateway', isTR ? 'Gateway sil' : 'Remove gateway', '(config-if)#'],
        ['ip helper-address <ip>', isTR ? 'DHCP relay' : 'Set DHCP relay', '(config-if)#'],
        ['no ip helper-address', isTR ? 'DHCP relay sil' : 'Remove DHCP relay', '(config-if)#'],
        ['ip verify source', isTR ? 'IP Source Guard' : 'Enable Source Guard', '(config-if)#'],
        ['ip dhcp snooping trust', isTR ? 'G├╝venli DHCP portu' : 'DHCP snooping trust', '(config-if)#'],
        ['ip arp inspection trust', isTR ? 'G├╝venli ARP portu' : 'ARP inspection trust', '(config-if)#'],
        ['storm-control {b|m|u} lvl', isTR ? 'F─▒rt─▒na kontrol├╝' : 'Storm control', '(config-if)#'],
        ['power inline {auto|static}', isTR ? 'PoE yap─▒land─▒rmas─▒' : 'Configure PoE', '(config-if)#'],
        ['bandwidth <kbps>', isTR ? 'Bant geni┼şli─şi' : 'Set bandwidth', '(config-if)#'],
        ['delay <tens-of-ms>', isTR ? 'Gecikme s├╝resi' : 'Set delay', '(config-if)#'],
        ['mls qos trust {cos|dscp}', isTR ? 'QoS g├╝ven durumu' : 'Set QoS trust', '(config-if)#'],
        ['mls qos cos <val>', isTR ? 'Default CoS de─şeri' : 'Set default CoS', '(config-if)#'],
        ['cdp enable', isTR ? 'CDP\'yi a├ğ (aray├╝z)' : 'Enable CDP (interface)', '(config-if)#'],
        ['no udld', isTR ? 'UDLD\'yi kapat' : 'Disable UDLD', '(config-if)#'],
        ['no ip proxy-arp', isTR ? 'Proxy ARP kapat' : 'Disable proxy ARP', '(config-if)#'],
        ['no keepalive', isTR ? 'Keepalive kapat' : 'Disable keepalive', '(config-if)#'],
        ['load-interval <sec>', isTR ? '─░statistik aral─▒─ş─▒' : 'Set load interval', '(config-if)#'],
        ['carrier-delay <ms>', isTR ? 'Carrier gecikmesi' : 'Set carrier delay', '(config-if)#'],
        ['channel-group <n> mode', isTR ? 'EtherChannel' : 'EtherChannel', '(config-if)#'],
        ['no channel-group', isTR ? 'EtherChannel sil' : 'Remove from channel', '(config-if)#'],
        ['encapsulation hdlc', isTR ? 'HDLC kaps├╝lleme (seri)' : 'HDLC encapsulation (serial)', '(config-if)#'],
        ['encapsulation ppp', isTR ? 'PPP kaps├╝lleme (seri)' : 'PPP encapsulation (serial)', '(config-if)#'],
        ['clock rate <bps>', isTR ? 'Saat h─▒z─▒ (DCE seri)' : 'Clock rate (DCE serial)', '(config-if)#'],
        ['ppp authentication pap', isTR ? 'PPP PAP kimlik do─şrulama' : 'PPP PAP authentication', '(config-if)#'],
        ['ppp authentication chap', isTR ? 'PPP CHAP kimlik do─şrulama' : 'PPP CHAP authentication', '(config-if)#'],
        ['ppp pap sent-username <u> <p>', isTR ? 'PAP kullan─▒c─▒ ad─▒/┼şifre' : 'PAP username/password', '(config-if)#'],
        ['ip access-group <id> {in|out}', isTR ? 'ACL uygula' : 'Apply ACL', '(config-if)#'],
        ['ip nat {inside|outside}', isTR ? 'NAT taraf─▒ se├ğ' : 'Set NAT side', '(config-if)#'],
        ['standby <g> ip <vip>', isTR ? 'HSRP Virtual IP' : 'HSRP Virtual IP', '(config-if)#'],
        ['standby <g> priority <p>', isTR ? 'HSRP ├ûnceli─şi' : 'HSRP Priority', '(config-if)#'],
        ['monitor session <n>', isTR ? 'SPAN/RSPAN' : 'Configure SPAN/RSPAN', '(config-if)#'],
      ]
    },
    {
      id: 'wireless',
      icon: Wifi,
      title: isTR ? 'Kablosuz (WiFi / Dot11)' : 'Wireless (WiFi / Dot11)',
      type: 'commands',
      cmds: [
        ['dot11 ssid <name>', isTR ? 'SSID yap─▒land─▒rmas─▒na gir' : 'Enter SSID config', '(config)#'],
        ['authentication open', isTR ? 'A├ğ─▒k kimlik do─şrulama' : 'Open authentication', '(config-ssid)#'],
        ['authentication shared', isTR ? 'Payla┼ş─▒ml─▒ kimlik do─şrulama' : 'Shared authentication', '(config-ssid)#'],
        ['authentication network-eap', isTR ? 'EAP kimlik do─şrulama' : 'EAP authentication', '(config-ssid)#'],
        ['authentication key-management wpa version {1|2}', isTR ? 'WPA anahtar y├Ânetimi' : 'WPA key management', '(config-ssid)#'],
        ['wpa-psk ascii <key>', isTR ? 'WPA ├Ân-payla┼ş─▒ml─▒ anahtar' : 'WPA pre-shared key', '(config-ssid)#'],
        ['guest-mode', isTR ? 'SSID\'yi yay─▒nla (Beacon)' : 'Broadcast SSID (Beacon)', '(config-ssid)#'],
        ['no guest-mode', isTR ? 'SSID yay─▒n─▒n─▒ kapat' : 'Stop SSID broadcast', '(config-ssid)#'],
        ['wlan <name> <id> <ssid>', isTR ? 'WLAN olu┼ştur (kontrol cihaz─▒)' : 'Create WLAN (controller)', '(config)#'],
        ['no wlan <id>', isTR ? 'WLAN sil' : 'Delete WLAN', '(config)#'],
        ['security wpa psk set-key ascii 0 <pass>', isTR ? 'WPA ┼şifresi ayarla (WLAN)' : 'Set WPA password (WLAN)', '(config-wlan)#'],
        ['interface Dot11Radio <n>', isTR ? 'Radyo aray├╝z├╝ne gir' : 'Enter radio interface', '(config)#'],
        ['encryption mode ciphers {aes-ccm|tkip}', isTR ? '┼Şifreleme y├Ântemi' : 'Encryption method', '(config-if)#'],
        ['ssid <name>', isTR ? 'SSID\'yi radyo aray├╝z├╝ne ba─şla' : 'Bind SSID to radio interface', '(config-if)#'],
        ['no ssid <name>', isTR ? 'SSID ba─şlant─▒s─▒n─▒ kald─▒r' : 'Remove SSID binding', '(config-if)#'],
        ['channel <num>', isTR ? 'RF kanal─▒ ayarla' : 'Set RF channel', '(config-if)#'],
        ['power local <mw>', isTR ? '─░letim g├╝c├╝ ayarla' : 'Set transmit power', '(config-if)#'],
        ['station-role {root|repeater|client}', isTR ? 'AP ├ğal─▒┼şma modu' : 'AP role mode', '(config-if)#'],
        ['mac-filter', isTR ? 'MAC filtrelemeyi a├ğ' : 'Enable MAC filtering', '(config-if)#'],
        ['no mac-filter', isTR ? 'MAC filtrelemeyi kapat' : 'Disable MAC filtering', '(config-if)#'],
        ['show dot11 associations', isTR ? 'Kablosuz istemcileri g├Âster' : 'Show wireless clients', '#'],
        ['show dot11 statistics', isTR ? 'Kablosuz istatistikleri' : 'Show wireless statistics', '#'],
      ]
    },
    {
      id: 'line',
      icon: Router,
      title: isTR ? 'Hat Yap─▒land─▒rmas─▒' : 'Line Config',
      type: 'commands',
      cmds: [
        ['line console 0', isTR ? 'Konsol hatt─▒' : 'Console line', '(config)#'],
        ['line vty 0 4', isTR ? 'VTY hatlar─▒ (0-4)' : 'VTY lines (0-4)', '(config)#'],
        ['line vty 5 15', isTR ? 'VTY hatlar─▒ (5-15)' : 'VTY lines (5-15)', '(config)#'],
        ['line aux 0', isTR ? 'Aux hatt─▒' : 'Auxiliary line', '(config)#'],
        ['password <pass>', isTR ? '┼Şifre ayarla' : 'Set password', '(config-line)#'],
        ['no password', isTR ? '┼Şifreyi sil' : 'Remove password', '(config-line)#'],
        ['login', isTR ? 'Giri┼ş kontrol├╝' : 'Enable login', '(config-line)#'],
        ['no login', isTR ? 'Giri┼ş kontrol├╝ kapat' : 'Disable login', '(config-line)#'],
        ['transport input {p}', isTR ? 'Giri┼ş protokolleri' : 'Input protocols', '(config-line)#'],
        ['transport output {p}', isTR ? '├ç─▒k─▒┼ş protokolleri' : 'Output protocols', '(config-line)#'],
        ['no transport input', isTR ? 'Giri┼şleri s─▒f─▒rla' : 'Reset transport input', '(config-line)#'],
        ['logging synchronous', isTR ? 'Senkron loglama' : 'Sync logging', '(config-line)#'],
        ['no logging synchronous', isTR ? 'Senkron log kapat' : 'Disable sync logging', '(config-line)#'],
        ['exec-timeout <m> [s]', isTR ? 'Zaman a┼ş─▒m─▒' : 'Exec timeout', '(config-line)#'],
        ['no exec-timeout', isTR ? 'Zaman a┼ş─▒m─▒ s─▒f─▒rla' : 'Reset exec timeout', '(config-line)#'],
        ['history size <n>', isTR ? 'Ge├ğmi┼ş boyutu' : 'Set history size', '(config-line)#'],
        ['no history', isTR ? 'Ge├ğmi┼şi kapat' : 'Disable history', '(config-line)#'],
        ['exec', isTR ? 'EXEC aktif' : 'Enable EXEC', '(config-line)#'],
        ['no exec', isTR ? 'EXEC pasif' : 'Disable EXEC', '(config-line)#'],
        ['autocommand <cmd>', isTR ? 'Otomatik komut' : 'Set auto-command', '(config-line)#'],
        ['no autocommand', isTR ? 'Otomatik komut sil' : 'Remove auto-command', '(config-line)#'],
        ['transport preferred {ssh|telnet|none}', isTR ? 'Tercih edilen protokol' : 'Preferred protocol', '(config-line)#'],
        ['privilege level <0-15>', isTR ? 'Yetki seviyesi' : 'Set privilege level', '(config-line)#'],
        ['session-limit <n>', isTR ? 'Oturum s─▒n─▒r─▒' : 'Session limit', '(config-line)#'],
        ['access-class <n> {in|out}', isTR ? 'ACL uygula (line)' : 'Apply access-class', '(config-line)#'],
        ['lockable', isTR ? 'Kilitlenebilir hat' : 'Enable lockable', '(config-line)#'],
      ]
    },
    {
      id: 'router',
      icon: Network,
      title: isTR ? 'Y├Ânlendirme (Routing)' : 'Routing Config',
      type: 'commands',
      cmds: [
        ['router rip', isTR ? 'RIP y├Ânlendirmesi' : 'Enable RIP', '(config)#'],
        ['router ospf [<id>]', isTR ? 'OSPF y├Ânlendirmesi' : 'Enable OSPF', '(config)#'],
        ['router eigrp <as>', isTR ? 'EIGRP y├Ânlendirmesi' : 'Enable EIGRP', '(config)#'],
        ['router bgp <as>', isTR ? 'BGP y├Ânlendirmesi' : 'Enable BGP', '(config)#'],
        ['no router {rip|ospf|eigrp|bgp}', isTR ? 'Y├Ânlendirmeyi kapat' : 'Disable routing', '(config)#'],
        ['network <ip> [wildcard]', isTR ? 'A─ş ekle (RIP/EIGRP)' : 'Add network (RIP/EIGRP)', '(config-router)#'],
        ['network <ip> area <id>', isTR ? 'OSPF a─ş─▒ ekle' : 'Add OSPF network', '(config-router)#'],
        ['neighbor <ip> remote-as <as>', isTR ? 'BGP kom┼şusu ekle' : 'Add BGP neighbor', '(config-router)#'],
        ['no neighbor <ip> remote-as', isTR ? 'BGP kom┼şusunu sil' : 'Remove BGP neighbor', '(config-router)#'],
        ['router-id <ip>', isTR ? 'Router ID ayarla' : 'Set router ID', '(config-router)#'],
        ['passive-interface <int>', isTR ? 'Pasif aray├╝z' : 'Passive interface', '(config-router)#'],
        ['no passive-interface <int>', isTR ? 'Pasif aray├╝z kald─▒r' : 'Remove passive interface', '(config-router)#'],
        ['default-info originate', isTR ? 'Varsay─▒lan rota' : 'Default route', '(config-router)#'],
        ['auto-summary', isTR ? 'Otomatik ├Âzetleme' : 'Auto-summary', '(config-router)#'],
        ['no auto-summary', isTR ? 'Otomatik ├Âzetlemeyi kapat' : 'Disable auto-summary', '(config-router)#'],
        ['ipv6 router rip <tag>', isTR ? 'IPv6 RIP y├Ânlendirmesi' : 'Enable IPv6 RIP', '(config)#'],
        ['ipv6 router ospf <id>', isTR ? 'IPv6 OSPF y├Ânlendirmesi' : 'Enable IPv6 OSPF', '(config)#'],
        ['no ipv6 router rip <tag>', isTR ? 'IPv6 RIP kapat' : 'Disable IPv6 RIP', '(config)#'],
        ['no ipv6 router ospf <id>', isTR ? 'IPv6 OSPF kapat' : 'Disable IPv6 OSPF', '(config)#'],
        ['show ip route', isTR ? 'Y├Ânlendirme tablosu' : 'Show routing table', '#'],
        ['show ip ospf [neighbor|interface]', isTR ? 'OSPF detaylar─▒' : 'Show OSPF details', '#'],
        ['show ip protocols', isTR ? 'Y├Ânlendirme protokolleri' : 'Show routing protocols', '#'],
        ['show ip eigrp neighbors', isTR ? 'EIGRP kom┼şular─▒' : 'Show EIGRP neighbors', '#'],
        ['show ip bgp summary', isTR ? 'BGP ├Âzeti' : 'Show BGP summary', '#'],
        ['show ip bgp', isTR ? 'BGP tablosu' : 'Show BGP table', '#'],
        ['show ipv6 route', isTR ? 'IPv6 y├Ânlendirme tablosu' : 'Show IPv6 routing table', '#'],
        ['show ipv6 rip', isTR ? 'IPv6 RIP durumu' : 'Show IPv6 RIP status', '#'],
        ['show ipv6 ospf', isTR ? 'IPv6 OSPF durumu' : 'Show IPv6 OSPF status', '#'],
      ]
    },
    {
      id: 'dhcp',
      icon: Server,
      title: isTR ? 'DHCP Havuzu' : 'DHCP Pool Config',
      type: 'commands',
      cmds: [
        ['network <net> <mask>', isTR ? 'Havuz a─ş─▒' : 'Pool network', '(config-dhcp)#'],
        ['default-router <ip>', isTR ? 'Varsay─▒lan ge├ğit' : 'Default router', '(config-dhcp)#'],
        ['dns-server <ip>', isTR ? 'DNS sunucusu' : 'DNS server', '(config-dhcp)#'],
        ['lease {days|infinite}', isTR ? 'Kira s├╝resi' : 'Lease duration', '(config-dhcp)#'],
        ['domain-name <name>', isTR ? 'Alan ad─▒' : 'Domain name', '(config-dhcp)#'],
      ]
    },
    {
      id: 'show',
      icon: Eye,
      title: isTR ? 'Show Komutlar─▒' : 'Show Commands',
      type: 'commands',
      cmds: [
        ['show', isTR ? '├ûzet bilgi' : 'Display summary', '#'],
        ['show running-config', isTR ? '├çal─▒┼şan yap─▒land─▒rma' : 'Running config', '#'],
        ['show startup-config', isTR ? 'Ba┼şlang─▒├ğ yap─▒land─▒rmas─▒' : 'Startup config', '#'],
        ['show version', isTR ? 'Sistem bilgisi' : 'System version', '#'],
        ['show interfaces', isTR ? 'T├╝m aray├╝zler' : 'Display all interfaces', '#'],
        ['show interfaces trunk', isTR ? 'Trunk aray├╝zler' : 'Display trunks', '#'],
        ['show interface <name>', isTR ? 'Aray├╝z ayr─▒nt─▒s─▒' : 'Interface details', '#'],
        ['show ip interface brief', isTR ? 'Aray├╝z ├Âzeti' : 'IP interface brief', '#'],
        ['show ip interface', isTR ? 'IP aray├╝z detay' : 'IP interface details', '#'],
        ['show ip protocols', isTR ? 'Y├Ânlendirme protokolleri' : 'IP routing protocols', '#'],
        ['show ip ospf [neighbor|interface]', isTR ? 'OSPF detaylar─▒' : 'OSPF details', '#'],
        ['show ip nat translations', isTR ? 'NAT ├ğevirileri' : 'NAT translations', '#'],
        ['show ip nat statistics', isTR ? 'NAT istatistikleri' : 'NAT statistics', '#'],
        ['show standby [brief]', isTR ? 'HSRP durumu' : 'HSRP status', '#'],
        ['show ip arp', isTR ? 'ARP tablosu' : 'ARP table', '#'],
        ['show ipv6 interface brief', isTR ? 'IPv6 aray├╝z ├Âzeti' : 'IPv6 interface brief', '#'],
        ['show vlan [brief]', isTR ? 'VLAN listesi' : 'VLAN list', '#'],
        ['show mac address-table', isTR ? 'MAC tablosunu g├Âster' : 'Show MAC address table', '#'],
        ['show cdp neighbors', isTR ? 'CDP kom┼şular─▒' : 'CDP neighbors', '#'],
        ['show ip route', isTR ? 'Y├Ânlendirme tablosu' : 'Routing table', '#'],
        ['show clock', isTR ? 'Sistem saati' : 'Display system clock', '#'],
        ['show flash', isTR ? 'Flash i├ğeri─şi' : 'Display flash', '#'],
        ['show boot', isTR ? 'Boot bilgisi' : 'Display boot info', '#'],
        ['show spanning-tree', isTR ? 'STP durumu' : 'STP status', '#'],
        ['show port-security', isTR ? 'Port g├╝venli─şi' : 'Port security status', '#'],
        ['show ssh', isTR ? 'SSH durumu' : 'SSH status', '#'],
        ['show wireless', isTR ? 'Kablosuz durumu' : 'Display wireless status', '#'],
        ['show ip dhcp snooping', isTR ? 'DHCP snooping' : 'Display DHCP snooping', '#'],
        ['show ip dhcp pool', isTR ? 'DHCP havuzlar─▒' : 'Display DHCP pools', '#'],
        ['show ip dhcp binding', isTR ? 'DHCP atamalar─▒' : 'DHCP bindings', '#'],
        ['show ip verify source', isTR ? 'Source Guard durumu' : 'IP source guard status', '#'],
        ['show ip source binding', isTR ? 'Source bindingleri' : 'IP source bindings', '#'],
        ['show ip arp inspection', isTR ? 'ARP denetimi' : 'ARP inspection status', '#'],
        ['show interfaces status', isTR ? 'Aray├╝z durumu' : 'Display port status', '#'],
        ['show storm-control', isTR ? 'F─▒rt─▒na kontrol├╝' : 'Storm control status', '#'],
        ['show monitor', isTR ? 'SPAN oturumlar─▒' : 'SPAN sessions', '#'],
        ['show udld', isTR ? 'UDLD durumu' : 'UDLD status', '#'],
        ['show cdp', isTR ? 'CDP bilgisi' : 'Display CDP info', '#'],
        ['show vtp status', isTR ? 'VTP durumu' : 'Display VTP status', '#'],
        ['show etherchannel', isTR ? 'EtherChannel' : 'Display EtherChannel', '#'],
        ['show arp', isTR ? 'ARP tablosu' : 'ARP table', '#'],
        ['show mls qos', isTR ? 'QoS durumu' : 'Display QoS status', '#'],
        ['show sdm prefer', isTR ? 'SDM ┼şablonu' : 'Display SDM template', '#'],
        ['show access-lists', isTR ? 'Eri┼şim listeleri' : 'Display access lists', '#'],
        ['show mac access-lists', isTR ? 'MAC eri┼şim listeleri' : 'Display MAC ACLs', '#'],
        ['show history', isTR ? 'Komut ge├ğmi┼şi' : 'Display command history', '#'],
        ['show users', isTR ? 'Kullan─▒c─▒lar' : 'Connected users', '#'],
        ['show environment', isTR ? 'Donan─▒m durumu' : 'Display hardware status', '#'],
        ['show inventory', isTR ? 'Donan─▒m envanteri' : 'Display inventory', '#'],
        ['show errdisable recovery', isTR ? 'Hata kurtarma' : 'Display errdisable', '#'],
        ['show debug', isTR ? 'Debug durumu' : 'Display debug status', '#'],
        ['show processes', isTR ? '─░┼şlemler (CPU)' : 'Display processes', '#'],
        ['show memory', isTR ? 'Bellek kullan─▒m─▒' : 'Display memory usage', '#'],
        ['show system mtu', isTR ? 'MTU ayarlar─▒' : 'Display MTU settings', '#'],
        ['show ntp status', isTR ? 'NTP durumu' : 'Display NTP status', '#'],
        ['show snmp', isTR ? 'SNMP bilgisi' : 'Display SNMP info', '#'],
        ['show archive', isTR ? 'Ar┼şiv durumu' : 'Display archive status', '#'],
        ['show alias', isTR ? 'Alias listesi' : 'Display command aliases', '#'],
        ['show diagnostic', isTR ? 'Te┼şhis sonu├ğlar─▒' : 'Display diagnostics', '#'],
        ['show lldp', isTR ? 'LLDP kom┼şular─▒' : 'Display LLDP info', '#'],
        ['show authentication', isTR ? 'Kimlik do─şrulama' : 'Display auth sessions', '#'],
        ['show running-config interface <name>', isTR ? 'Aray├╝z yap─▒land─▒rmas─▒' : 'Show interface config', '#'],
        ['show spanning-tree interface <name>', isTR ? 'Aray├╝z STP durumu' : 'Show interface STP status', '#'],
        ['show ip ssh', isTR ? 'SSH yap─▒land─▒rmas─▒' : 'Show SSH configuration', '#'],
        ['show cdp neighbors detail', isTR ? 'CDP kom┼şular─▒ detayl─▒' : 'Show CDP neighbor details', '#'],
        ['show policy-map [name]', isTR ? 'Politika haritas─▒' : 'Show policy map', '#'],
        ['show policy-map interface', isTR ? 'Aray├╝z politika haritas─▒' : 'Show interface policy map', '#'],
        ['show class-map [name]', isTR ? 'S─▒n─▒f haritas─▒' : 'Show class map', '#'],
        ['show qos interface <name>', isTR ? 'Aray├╝z QoS durumu' : 'Show interface QoS', '#'],
        ['show queuing interface <name>', isTR ? 'Aray├╝z kuyruk durumu' : 'Show interface queuing', '#'],
        ['show ip ospf interface <name>', isTR ? 'OSPF aray├╝z durumu' : 'Show OSPF interface', '#'],
        ['show ipv6 route', isTR ? 'IPv6 y├Ânlendirme tablosu' : 'Show IPv6 routing table', '#'],
        ['show ipv6 dhcp pool', isTR ? 'IPv6 DHCP havuzu' : 'Show IPv6 DHCP pool', '#'],
        ['show mac address-table static', isTR ? 'Statik MAC adresleri' : 'Show static MAC addresses', '#'],
        ['show sessions', isTR ? 'Aktif oturumlar' : 'Show active sessions', '#'],
        ['show ntp associations', isTR ? 'NTP ili┼şkileri' : 'Show NTP associations', '#'],
        ['show hosts', isTR ? 'Host tablosu' : 'Show host table', '#'],
        ['show debugging', isTR ? 'Hata ay─▒klama durumu' : 'Show debug status', '#'],
        ['show errdisable detect', isTR ? 'Hata alg─▒lama ayarlar─▒' : 'Show errdisable detection', '#'],
        ['show redundancy', isTR ? 'Yedeklilik durumu' : 'Show redundancy status', '#'],
        ['show controllers <type/n>', isTR ? 'Denetleyici durumu' : 'Show controller status', '#'],
        ['show banner motd', isTR ? 'MOTD banner mesaj─▒' : 'Show MOTD banner', '#'],
        ['show iot sensors', isTR ? 'IoT sens├Âr listesi' : 'Show IoT sensors', '#'],
        ['show iot status', isTR ? 'IoT cihaz durumu' : 'Show IoT device status', '#'],
      ]
    },
    {
      id: 'keyboard',
      icon: Keyboard,
      title: isTR ? 'Klavye K─▒sayollar─▒' : 'Keyboard Shortcuts',
      type: 'info',
      cmds: [
        // Canvas
        ['Ctrl + Z', isTR ? 'Geri al' : 'Undo'],
        ['Ctrl + Y / Ctrl + Shift + Z', isTR ? 'Yeniden yap' : 'Redo'],
        ['Ctrl + C', isTR ? 'Se├ğili cihaz─▒ kopyala' : 'Copy selected device'],
        ['Ctrl + X', isTR ? 'Se├ğili cihaz─▒ kes' : 'Cut selected device'],
        ['Ctrl + V', isTR ? 'Yap─▒┼şt─▒r' : 'Paste'],
        ['Ctrl + A', isTR ? 'T├╝m├╝n├╝ se├ğ' : 'Select all'],
        ['Delete / Backspace', isTR ? 'Se├ğili ├Â─şeyi sil' : 'Delete selected'],
        ['Escape', isTR ? 'Se├ğimi iptal et / Modu kapat' : 'Cancel selection / Close mode'],
        ['Ctrl + Scroll', isTR ? 'Yak─▒nla┼şt─▒r / Uzakla┼şt─▒r' : 'Zoom in / out'],
        ['Space + S├╝r├╝kle', isTR ? 'Canvas\'─▒ kayd─▒r' : 'Pan canvas'],
        ['F1', isTR ? 'Yard─▒m panelini a├ğ / kapat' : 'Open / close help panel'],
        // Ping packet panel
        ['P', isTR ? 'Paket analizi: Oynat / Duraklat' : 'Packet analysis: Play / Pause'],
        ['N', isTR ? 'Paket analizi: Sonraki Hop (duraklat─▒ld─▒─ş─▒nda)' : 'Packet analysis: Next Hop (when paused)'],
      ]
    },
    {
      id: 'desktop',
      icon: Terminal,
      title: isTR ? 'Masa├╝st├╝ Bilgisayar' : 'Desktop Computer',
      type: 'commands',
      cmds: [
        ['ipconfig [/all] [/release] [/renew]', isTR ? 'IP yap─▒land─▒rmas─▒' : 'IP configuration'],
        ['ping <host>', isTR ? 'Ba─şlant─▒ testi' : 'Test connectivity'],
        ['tracert <host>', isTR ? 'Rota izleme' : 'Trace route'],
        ['netstat', isTR ? 'A─ş istatistikleri' : 'Network statistics'],
        ['nslookup <domain>', isTR ? 'DNS sorgusu' : 'DNS lookup'],
        ['telnet <host> [port]', isTR ? 'Telnet ba─şlant─▒s─▒' : 'Telnet connection'],
        ['ssh [-l user] <host>', isTR ? 'SSH ba─şlant─▒s─▒' : 'SSH connection'],
        ['curl / wget <url>', isTR ? 'Web sayfas─▒ g├Âr├╝nt├╝le' : 'View web page'],
        ['arp -a', isTR ? 'ARP tablosu' : 'ARP table'],
        ['hostname', isTR ? 'Bilgisayar ad─▒' : 'Computer name'],
        ['dir', isTR ? 'Dosya listesi' : 'Directory listing'],
        ['ver', isTR ? 'Versiyon bilgisi' : 'Version info'],
        ['cls', isTR ? 'Ekran─▒ temizle' : 'Clear screen'],
        ['snake / yilan', isTR ? 'Y─▒lan Oyunu' : 'Snake Game'],
        ['help / ?', isTR ? 'PC komut yard─▒m─▒' : 'Desktop command help'],
      ]
    },
    {
      id: 'network-terms',
      icon: Book,
      title: isTR ? 'A─ş Terimleri' : 'Network Terms',
      type: 'info',
      cmds: [
        ['IP Address', isTR ? 'A─şda cihaz─▒ tan─▒mlayan benzersiz say─▒sal adres (├Ârn: 192.168.1.1)' : 'Unique numerical address identifying a device on a network (e.g., 192.168.1.1)'],
        ['MAC Address', isTR ? 'A─ş kart─▒n─▒n fiziksel adresi, 48-bit onalt─▒l─▒ format (├Ârn: 00-1a-2b-3c-4d-5e)' : 'Physical address of network interface, 48-bit hex format (e.g., 00-1a-2b-3c-4d-5e)'],
        ['Gateway', isTR ? 'Farkl─▒ a─şlara eri┼şim sa─şlayan cihaz, genellikle router' : 'Device providing access to other networks, typically a router'],
        ['Subnet Mask', isTR ? 'IP adresinin a─ş ve host k─▒s─▒mlar─▒n─▒ ay─▒ran say─▒ (├Ârn: 255.255.255.0)' : 'Separates network and host portions of IP address (e.g., 255.255.255.0)'],
        ['Router', isTR ? 'A─şlar aras─▒nda veri y├Ânlendiren cihaz' : 'Device that routes data between networks'],
        ['Switch', isTR ? 'Yerel a─şda cihazlar─▒ birbirine ba─şlayan cihaz' : 'Device connecting devices within local network'],
        ['Firewall', isTR ? 'Yetkisiz a─ş eri┼şimini engelleyen g├╝venlik sistemi' : 'Security system blocking unauthorized network access'],
        ['Port', isTR ? 'Hizmet ve protokolleri tan─▒mlayan say─▒sal kimlik (SSH: 22, HTTP: 80, HTTPS: 443)' : 'Numerical identifier for services (SSH: 22, HTTP: 80, HTTPS: 443)'],
        ['Protocol', isTR ? 'A─ş ileti┼şimi i├ğin kurallar─▒ tan─▒mlayan standart' : 'Standard defining rules for network communication'],
        ['Bandwidth', isTR ? 'A─ş ba─şlant─▒s─▒n─▒n saniye cinsinden veri aktar─▒m kapasitesi (Mbps, Gbps)' : 'Network link capacity measured in data transfer per second (Mbps, Gbps)'],
        ['Ping', isTR ? 'Cihazlar aras─▒ndaki ileti┼şim h─▒z─▒, milisaniye cinsinden' : 'Communication speed between devices, measured in milliseconds'],
        ['Packet', isTR ? 'A─şda iletilen veri biriminin ad─▒' : 'Unit of data transmitted over network'],
        ['VLAN', isTR ? 'Fiziksel a─ş─▒ mant─▒ksal gruplara b├Âlen sistem' : 'System partitioning physical network into logical groups'],
        ['Proxy', isTR ? '─░stemci ile sunucu aras─▒nda arac─▒ g├Ârev yapan sunucu' : 'Server acting as intermediary between client and server'],
        ['VPN', isTR ? '─░nternet ├╝zerinden g├╝venli ve ┼şifreli ba─şlant─▒' : 'Secure encrypted connection over the internet'],
      ]
    },
    {
      id: 'abbreviations',
      icon: Zap,
      title: isTR ? 'A─ş K─▒saltmalar─▒' : 'Network Abbreviations',
      type: 'info',
      cmds: [
        ['DHCP', isTR ? 'Dynamic Host Configuration Protocol - IP adreslerini otomatik olarak atayan protokol' : 'Dynamic Host Configuration Protocol - automatically assigns IP addresses'],
        ['DNS', isTR ? 'Domain Name System - Alan adlar─▒n─▒ IP adreslerine ├ğeviren sistem' : 'Domain Name System - converts domain names to IP addresses'],
        ['ARP', isTR ? 'Address Resolution Protocol - IP adresini MAC adresine ├ğeviren protokol' : 'Address Resolution Protocol - converts IP to MAC address'],
        ['TCP', isTR ? 'Transmission Control Protocol - G├╝venilir, ba─şlant─▒ tabanl─▒ protokol' : 'Transmission Control Protocol - reliable, connection-based protocol'],
        ['UDP', isTR ? 'User Datagram Protocol - H─▒zl─▒, ba─şlant─▒s─▒z protokol' : 'User Datagram Protocol - fast, connectionless protocol'],
        ['SSH', isTR ? 'Secure Shell - G├╝venli uzak ba─şlant─▒ protokol├╝' : 'Secure Shell - secure remote connection protocol'],
        ['HTTP', isTR ? 'HyperText Transfer Protocol - Web sayfalar─▒ i├ğin protokol' : 'HyperText Transfer Protocol - protocol for web pages'],
        ['HTTPS', isTR ? 'HTTP Secure - ┼Şifreli HTTP protokol├╝' : 'HTTP Secure - encrypted HTTP protocol'],
        ['FTP', isTR ? 'File Transfer Protocol - Dosya aktar─▒m─▒ protokol├╝' : 'File Transfer Protocol - file transfer protocol'],
        ['SFTP', isTR ? 'SSH File Transfer Protocol - G├╝venli dosya aktar─▒m─▒' : 'SSH File Transfer Protocol - secure file transfer'],
        ['SMTP', isTR ? 'Simple Mail Transfer Protocol - E-posta g├Ânderme protokol├╝' : 'Simple Mail Transfer Protocol - email sending protocol'],
        ['POP3', isTR ? 'Post Office Protocol 3 - E-posta alma protokol├╝' : 'Post Office Protocol 3 - email receiving protocol'],
        ['IMAP', isTR ? 'Internet Message Access Protocol - E-posta y├Ânetimi protokol├╝' : 'Internet Message Access Protocol - email management protocol'],
        ['QoS', isTR ? 'Quality of Service - Hizmet Kalitesi' : 'Quality of Service - network traffic priority'],
        ['MTU', isTR ? 'Maximum Transmission Unit - Maksimum Aktar─▒m Birimi' : 'Maximum Transmission Unit - maximum packet size'],
        ['RFC', isTR ? 'Request for Comments - ─░nternet standartlar─▒n─▒ tan─▒mlayan dok├╝manlard─▒r' : 'Request for Comments - internet standard documentation'],
        ['CIDR', isTR ? 'Classless Inter-Domain Routing - IP bloklar─▒ g├Âsterim y├Ântemi' : 'Classless Inter-Domain Routing - IP notation method'],
        ['ICMP', isTR ? 'Internet Control Message Protocol - A─ş diagnostik protokol├╝' : 'Internet Control Message Protocol - network diagnostic protocol'],
        ['MAC', isTR ? 'Media Access Control - A─ş kart─▒n─▒n fiziksel adresi, 48-bit onalt─▒l─▒ format (├Ârn: 00-1a-2b-3c-4d-5e)' : 'Media Access Control - physical address of network interface, 48-bit hex format (e.g., 00-1a-2b-3c-4d-5e)'],
        ['IP', isTR ? 'Internet Protocol - A─şda cihaz─▒ tan─▒mlayan benzersiz say─▒sal adres (├Ârn: 192.168.1.1)' : 'Internet Protocol - unique numerical address identifying a device on a network (e.g., 192.168.1.1)'],
        ['NAT', isTR ? 'Network Address Translation - A─ş adresi d├Ân├╝┼şt├╝rme' : 'Network Address Translation - translates private IPs to public'],
        ['ACL', isTR ? 'Access Control List - Eri┼şim kontrol listesi' : 'Access Control List - filters network traffic'],
        ['VPN', isTR ? 'Virtual Private Network - ─░nternet ├╝zerinden g├╝venli ve ┼şifreli ba─şlant─▒' : 'Virtual Private Network - secure encrypted connection over the internet'],
        ['WLAN', isTR ? 'Wireless Local Area Network - Kablosuz yerel a─ş' : 'Wireless Local Area Network - wireless local network'],
        ['SSID', isTR ? 'Service Set Identifier - Kablosuz a─ş ad─▒' : 'Service Set Identifier - wireless network name'],
        ['STP', isTR ? 'Spanning Tree Protocol - A─ş halkalar─▒n─▒ ├Ânleyen protokol' : 'Spanning Tree Protocol - prevents network loops'],
        ['OSPF', isTR ? 'Open Shortest Path First - Dinamik y├Ânlendirme protokol├╝' : 'Open Shortest Path First - dynamic routing protocol'],
        ['RIP', isTR ? 'Routing Information Protocol - Basit y├Ânlendirme protokol├╝' : 'Routing Information Protocol - basic routing protocol'],
        ['BGP', isTR ? 'Border Gateway Protocol - InterASA y├Ânlendirme protokol├╝' : 'Border Gateway Protocol - inter-AS routing protocol'],
        ['SNMP', isTR ? 'Simple Network Management Protocol - A─ş y├Ânetim protokol├╝' : 'Simple Network Management Protocol - network management protocol'],
        ['NTP', isTR ? 'Network Time Protocol - A─ş zaman senkronizasyon' : 'Network Time Protocol - network time synchronization'],
        ['LDAP', isTR ? 'Lightweight Directory Access Protocol - Kullan─▒c─▒ dizin hizmeti' : 'Lightweight Directory Access Protocol - directory service protocol'],
        ['SSL/TLS', isTR ? 'Secure Socket Layer / Transport Layer Security - ┼Şifreleme protokol├╝' : 'Secure Socket Layer / Transport Layer Security - encryption protocol'],
        ['L2TP', isTR ? 'Layer 2 Tunneling Protocol - T├╝nel olu┼şturma protokol├╝' : 'Layer 2 Tunneling Protocol - tunneling protocol'],
        ['GRE', isTR ? 'Generic Routing Encapsulation - Jenerik y├Ânlendirme protokol├╝' : 'Generic Routing Encapsulation - generic tunneling protocol'],
      ]
    },
  ];
}
